INSERT INTO `app_codigos_grupo_investigacion` (`id`, `codigo`) VALUES
(1, 'COL0153676'),
(2, 'COL0085647'),
(3, 'COL0106783'),
(4, 'COL0110481'),
(5, 'COL0113017'),
(6, 'COL0113975'),
(7, 'COL0129409'),
(8, 'COL0131024'),
(9, 'COL0133799'),
(10, 'COL0146626'),
(11, 'COL0149529'),
(12, 'COL0149869'),
(13, 'COL0150772'),
(14, 'COL0151199'),
(15, 'COL0158921'),
(16, 'COL0163494'),
(17, 'COL0179313'),
(18, 'COL0160339'),
(19, 'COL0147712'),
(20, 'COL0147991'),
(21, 'COL0148246'),
(22, 'COL0148273'),
(23, 'COL0116654'),
(24, 'COL0150389'),
(25, 'COL0152427'),
(26, 'COL0152739'),
(27, 'COL0152937'),
(28, 'COL0157352'),
(29, 'COL0158019'),
(30, 'COL0162236'),
(31, 'COL0102695'),
(32, 'COL0129797'),
(33, 'COL0135328'),
(34, 'COL0153193'),
(35, 'COL0154978'),
(36, 'COL0161426'),
(37, 'COL0160536'),
(38, 'COL0149369'),
(39, 'COL0150487'),
(40, 'COL0141469'),
(41, 'COL0039958'),
(42, 'COL0149637'),
(43, 'COL0192825'),
(44, 'COL0160376'),
(45, 'COL0151189'),
(46, 'COL0154548'),
(47, 'COL0157577'),
(48, 'COL0138544'),
(49, 'COL0144004'),
(50, 'COL0150244'),
(51, 'COL0160438'),
(52, 'COL0164025'),
(53, 'COL0166807'),
(54, 'COL0133996'),
(55, 'COL0146223'),
(56, 'COL0148068'),
(57, 'COL0149305'),
(58, 'COL0150478'),
(59, 'COL0150899'),
(60, 'COL0152356'),
(61, 'COL0154539'),
(62, 'COL0157835'),
(63, 'COL0158663'),
(64, 'COL0160287'),
(65, 'COL0160607'),
(66, 'COL0160616'),
(67, 'COL0162871'),
(68, 'COL0163529'),
(69, 'COL0147276'),
(70, 'COL0153719'),
(71, 'COL0182408'),
(72, 'COL0151018'),
(73, 'COL0039288'),
(74, 'COL0149439'),
(75, 'COL0149468'),
(76, 'COL0150674'),
(77, 'COL0164713'),
(78, 'COL0155376'),
(79, 'COL0157737'),
(80, 'COL0110285'),
(81, 'COL0156739'),
(82, 'COL0150057'),
(83, 'COL0157906'),
(84, 'COL0192754'),
(85, 'COL0160679'),
(86, 'COL0171834'),
(87, 'COL0153709'),
(88, 'COL0117491'),
(89, 'COL0149628'),
(90, 'COL0153433'),
(91, 'COL0149566'),
(92, 'COL0153291'),
(93, 'COL0163609'),
(94, 'COL0156149'),
(95, 'COL0056672'),
(96, 'COL0133029'),
(97, 'COL0135139'),
(98, 'COL0149501'),
(99, 'COL0150932'),
(100, 'COL0152098'),
(101, 'COL0154486'),
(102, 'COL0156462'),
(103, 'COL0155044'),
(104, 'COL0112154'),
(105, 'COL0149225'),
(106, 'COL0149388'),
(107, 'COL0041052'),
(108, 'COL0104635'),
(109, 'COL0112332'),
(110, 'COL0125779'),
(111, 'COL0143188'),
(112, 'COL0149323'),
(113, 'COL0150745'),
(114, 'COL0156229'),
(115, 'COL0158699'),
(116, 'COL0165784'),
(117, 'COL0189276'),
(118, 'COL0171843'),
(119, 'COL0164249');


INSERT INTO `app_diciplina_subarea` (`id`, `nombre`) VALUES
(1, 'Matemáticas puras'),
(2, 'Matemáticas aplicadas'),
(3, 'Estadística y probabilidades (investigación en metodologías)'),
(4, 'Ciencias de la Computación'),
(5, 'Ciencias de la Información y Bioinformática'),
(6, 'Física Atómica, Molecular y Química'),
(7, 'Física de la Materia'),
(8, 'Física de Partículas y Campos'),
(9, 'Física Nuclear'),
(10, 'Física de Plasmas y Fluídos'),
(11, 'Óptica'),
(12, 'Acústica'),
(13, 'Astronomía'),
(14, 'Química Orgánica'),
(15, 'Química Inorgánica y Nuclear'),
(16, 'Química Física'),
(17, 'Ciencias de los Polímeros'),
(18, 'Electroquímica'),
(19, 'Química de los Coloides'),
(20, 'Química Analítica'),
(21, 'Geociencias (Multidisciplinario)'),
(22, 'Mineralogía'),
(23, 'Paleontología'),
(24, 'Geoquímica y Geofísica'),
(25, 'Geografía Física'),
(26, 'Geología'),
(27, 'Vulcanología'),
(28, 'Ciencias del Medio Ambiente'),
(29, 'Meteorología y Ciencias Atmosféricas'),
(30, 'Investigación del Clima'),
(31, 'Oceanografía, Hidrología y Recursos del Agua'),
(32, 'Métodos de Investigación en Bioquímica'),
(33, 'Biofísica'),
(34, 'Genética y Herencia'),
(35, 'Biología Reproductiva'),
(36, 'Biología del Desarrollo'),
(37, 'Botánica y Ciencias de las Plantas'),
(38, 'Zoología, Ornitología, Entomología, Ciencias Biológicas del Comportamiento'),
(39, 'Biología Marina y del Agua'),
(40, 'Ecología'),
(41, 'Conservación de la Biodiversidad'),
(42, 'Biología (Teórica, Matemática, Criobiología, Evolutiva)'),
(43, 'Otras Biologías'),
(44, 'Biología Celular'),
(45, 'Bioquímica y Biología Molecular'),
(46, 'Microbiología'),
(47, 'Virología'),
(48, 'Micología'),
(49, 'Biotecnología Medioambiental'),
(50, 'Bioremediación, biotecnología para el diagnóstico (chips ADN y biosensores) en manejo ambiental'),
(51, 'Ética relacionada con Biotecnología Medioambiental'),
(52, 'Biotecnología Industrial'),
(53, 'Tecnologías de Bioprocesamiento, Biocatálisis, Fermentación'),
(54, 'Bioproductos (productos que se manufacturan usando biotecnología), biomateriales, bioplásticos, biocombustibles, materiales nuevos bioderivados, químicos finos bioderivados'),
(55, 'Otras Ciencias Naturales'),
(56, 'Nanomateriales (producción y propiedades)'),
(57, 'Nanoprocesos (aplicaciones a nanoescala)'),
(58, 'Ingeniería Civil'),
(59, 'Ingeniería Arquitectónica'),
(60, 'Ingeniería de la Construcción'),
(61, 'Ingeniería Estructural y Municipal'),
(62, 'Ingeniería del Transporte'),
(63, 'Ingeniería petróleos, minas, geología'),
(64, 'Ingeniería Eléctrica y Electrónica'),
(65, 'Robótica y Control Automático'),
(66, 'Automatización y Sistemas de Control'),
(67, 'Energías alternativas'),
(68, 'Ingeniería Mecánica'),
(69, 'Mecánica Aplicada'),
(70, 'Termodinámica'),
(71, 'Ingeniería Aeroespacial'),
(72, 'Ingeniería Nuclear'),
(73, 'Ingeniería del Audio'),
(74, 'Ingeniería de Sistemas y Comunicaciones'),
(75, 'Telecomunicaciones'),
(76, 'Hardware y Arquitectura de Computadores'),
(77, 'Ingeniería Química (Plantas y Productos)'),
(78, 'Ingeniería de Procesos'),
(79, 'Ingeniería Mecánica'),
(80, 'Cerámicos'),
(81, 'Recubrimientos y películas'),
(82, 'Compuestos (Laminados, Plásticos Reforzados, Fibras Sintéticas y Naturales, etc.)'),
(83, 'Papel y Madera'),
(84, 'Textiles'),
(85, 'Ingeniería Médica'),
(86, 'Tecnología médica de laboratorio (análisis de muestras, tecnologías para el diagnóstico)'),
(87, 'Ingeniería Ambiental y Geológica e Geotécnicas'),
(88, 'Ingeniería del Petróleo (Combustibles, Aceites), Energía y Combustibles'),
(89, 'Sensores Remotos'),
(90, 'Minería y Procesamiento de Minerales'),
(91, 'Ingeniería Marina, Naves'),
(92, 'Ingeniería Oceanográfica'),
(93, 'Logística'),
(94, 'Ingeniería de Producción'),
(95, 'Ingeniería Industrial'),
(96, 'Diseño industrial'),
(97, 'Agroindustria alimentaria'),
(98, 'Agroindustria no alimentaria'),
(99, 'Alimentos y Bebidas'),
(100, 'Inteligencia artificial'),
(101, 'Internet de las cosas IoT'),
(102, 'Analítica de datos'),
(103, 'Big Data'),
(104, 'Transformación Digital'),
(105, 'Anatomía y Morfología'),
(106, 'Genética humana'),
(107, 'Inmunología'),
(108, 'Neurociencias'),
(109, 'Farmacología y Farmacia'),
(110, 'Medicina Química'),
(111, 'Toxicología'),
(112, 'Fisiología (incluye Citología)'),
(113, 'Patología'),
(114, 'Andrología'),
(115, 'Obstetricia y Ginecología'),
(116, 'Pediatría'),
(117, 'Cardiovascular'),
(118, 'Vascular Periférico'),
(119, 'Hematología'),
(120, 'Respiratoria'),
(121, 'Cuidado crítico y de Emergencia'),
(122, 'Anestesiología'),
(123, 'Ortopédica'),
(124, 'Cirugía'),
(125, 'Radiología, Medicina Nuclear y de imágenes'),
(126, 'Transplantes'),
(127, 'Odontología, Cirugía Oral y Medicina Oral'),
(128, 'Dermatología y Enfermedades Venéreas'),
(129, 'Alergias'),
(130, 'Reumatología'),
(131, 'Endocrinología y Metabolismo (Incluye Diabetes y Transtornos Hormonales)'),
(132, 'Gastroenterología y Hepatología'),
(133, 'Urología y nefrología'),
(134, 'Oncología'),
(135, 'Oftalmología'),
(136, 'Otorrinonaringología'),
(137, 'Psiquiatría'),
(138, 'Neurología clínica'),
(139, 'Geriatría'),
(140, 'Medicina General e Interna'),
(141, 'Otro temas de Medicina Clínica'),
(142, 'Medicina complementaria (sistemas alternativos)'),
(143, 'Ciencias del Cuidado de la Salud y Servicios (Administración de Hospitales, financiamiento)'),
(144, 'Políticas de Salud y Servicios'),
(145, 'Enfermería'),
(146, 'Nutrición y Dietas'),
(147, 'Salud Pública'),
(148, 'Medicina Tropical'),
(149, 'Parasitología'),
(150, 'Enfermedades Infecciosas'),
(151, 'Epidemiología'),
(152, 'Salud Ocupacional'),
(153, 'Ciencias del Deporte'),
(154, 'Ciencias Socio Biomédicas (Planificación Familiar, Salud Sexual, Efectos políticos y sociales de la investigación Biomédica)'),
(155, 'Ética'),
(156, 'Abuso de substancias'),
(157, 'Biotecnología relacionada con la salud'),
(158, 'Tecnologías para la manipulación de células, tejidos, Órganos o el organismo (Reproducción asistida)'),
(159, 'Tecnología para la Identificación y Funcionamiento del ADN, proteínas y encimas y como influencian la enfermedad'),
(160, 'Biomateriales (Relacionados con implantes, dispositivos, sensores)'),
(161, 'Ética relacionada con la Biomedicina'),
(162, 'Forénsicas'),
(163, 'Otras Ciencias Médicas'),
(164, 'Fonoaudiología'),
(165, 'Agricultura'),
(166, 'Forestal'),
(167, 'Pesca'),
(168, 'Ciencias del Suelo'),
(169, 'Horticultura y viticultura'),
(170, 'Agronomía'),
(171, 'Fitomejoramiento, Biotecnología'),
(172, 'Protección y nutrición de las plantas'),
(173, 'Maquinaria agrícola'),
(174, 'Pesca'),
(175, 'Pecuaria y otras'),
(176, 'Biotecnología (sembradíos y ganado), clonamiento de ganado, selección asistida, dignóstico (con chips ADN, biosensores)'),
(177, 'Psicología (incluye relaciones hombre-máquina)'),
(178, 'Psicología (incluye terapias de aprendizaje, habla, visual y otras discapacidades físicas y mentales)'),
(179, 'Economía'),
(180, 'Econometría'),
(181, 'Relaciones Industriales'),
(182, 'Negocios y Management'),
(183, 'Educación General (Incluye Capacitación, Pedagogía)'),
(184, 'Educación Especial (Para estudiantes dotados y aquellos con dificultades de aprendizaje)'),
(185, 'Sociologia'),
(186, 'Demografía'),
(187, 'Antropología'),
(188, 'Etnología'),
(189, 'Temas especiales (Estudio de Género, Temas Sociales, Estudios de la Familia, Trabajo Social)'),
(190, 'Derecho'),
(191, 'Penal'),
(192, 'Educación General (Incluye Capacitación, Pedagogía)'),
(193, 'Educación Especial (Para estudiantes dotados y aquellos con dificultades de aprendizaje)'),
(194, 'Ciencias Ambientales (Aspectos Sociales)'),
(195, 'Geografía Económica y Cultural'),
(196, 'Estudios Urbanos (Planificación y Desarrollo)'),
(197, 'Planificación del Transporte y Aspectos Sociales del Transporte'),
(198, 'Periodismo'),
(199, 'Ciencias de la Información (Aspectos Sociales)'),
(200, 'Bibliotecología'),
(201, 'Medios y Comunicación Social'),
(202, 'Ciencias Sociales, Interdisciplinaria'),
(203, 'Otras Ciencias Sociales'),
(204, 'Actividades de apropiación de la ciencia, la tecnología y cultura de la innovación dirigida a la comunidad académica'),
(205, 'Historia'),
(206, 'Arqueología'),
(207, 'Estudios Generales del Lenguaje'),
(208, 'Idiomas Específicos'),
(209, 'Estudios Literarios'),
(210, 'Teoría Literaria'),
(211, 'Literatura Específica'),
(212, 'Lingüística'),
(213, 'Historia de la Ciencia y Tecnología'),
(214, 'Otras historias especializadas'),
(215, 'Arte'),
(216, 'Historia del Arte'),
(217, 'Diseño Arquitectónico'),
(218, 'Artes de la Representación (Musicología, Ciencias del Teatro, Dramaturgia)'),
(219, 'Estudios del Folclor'),
(220, 'Estudios de Cine, Radio y Televisión'),
(221, 'Arquitectura y Urbanismo'),
(222, 'Diseño Industrial y otros diseños'),
(223, 'Otras Humanidades'),
(224, 'Filosofía'),
(225, 'Teología'),
(226, 'Artes visuales, escénicas, turismo, gastronomía, restauración, etc'),
(227, 'Editorial, fonográfica, audiovisual, etc'),
(228, 'Medios digitales, software, apps, animación, diseño, publicidad, joyería, moda y diseño, etc');


INSERT INTO `app_nombre_grupo_investigacion` (`id`, `nombre`) VALUES
(1, 'ARARA'),
(2, 'Grupo de Investigación La Salada CILS'),
(3, 'Grupo de Investigación en Innovación y Agroindustria (GIIA)'),
(4, 'Gestión de la Innovación y el Desarrollo Tecnológico GIDT'),
(5, 'GACIPE (Grupo de Investigacacion en Automatizacion,Comunicaciones Industriales , Pedagogia y Energias Alternativas)'),
(6, 'Materiales para el Mobiliario - MATERMOB'),
(7, 'BIOMATIC (Biomecánica, materiales, TICS, diseño y calidad para el sector cuero, plástico y caucho y sus cadenas productivas'),
(8, 'GIGAT-Grupo de Investigación en gerencia y aplicación de la ciencia y la Tecnología'),
(9, 'Ciencia, Investigación, Conocimiento, Aprendizaje y Sociedad (CICAS)'),
(10, 'GRUPO DE INVESTIGACIÓN, INNOVACIÓN Y DESARROLLO PARA LA SUBREGIÓN DEL URABÁ- ABIBE'),
(11, 'GIDOCA'),
(12, 'Grupo de Investigación red de construcción, infraestructura y servicios públicos-GIRCIS'),
(13, 'Grupo de Investigación Ciencia, Tecnología e Innovación en Salud (CITEISA)'),
(14, 'Grupo de Investigación aplicada a la Industria, al Textil y a la Química (GIAITEQ)'),
(15, 'INAMOD Grupo de Investigación Aplicada en Moda y Diseño'),
(16, 'GITECA: Grupo de Investigación Tecnológica Agropecuaria del Bajo Cauca'),
(17, 'GIMAB (Grupo de Investigación Minero Ambiental de El Bagre'),
(18, 'GIISATA Grupo de Investigación para la Innovación Social, Agroindustrial, Tecnológica y Ambiental Araucana'),
(19, 'GIPAMA - Mejoramiento de la Producción Primaria, Agroindustria y Medio Ambiente'),
(20, 'Arcadia'),
(21, 'CNCA'),
(22, 'Grupo de Investigación del Centro Industrial y de Aviación (GICI)'),
(23, 'Grupo de Investigación en Procesos de la Industria Petroquímica \"GIPIPQ\"'),
(24, 'GIBIOMAS'),
(25, 'SENA CINAFLUP'),
(26, 'GRUPO DE INVESTIGACION BIOTECNOLOGÍA E INNOVACIÓN (GIBEI)'),
(27, 'GRUPO DE INVESTIGACIÓN , INNOVACIÓN Y CONOCIMIENTO APLICADO DE BOYACÁ GICAB'),
(28, 'GICEMIN'),
(29, 'GRUPO DE INVESTIGACIÓN, INNOVACIÓN, DESARROLLO SOCIAL, EMPRESARIAL Y TECNOLÓGICO'),
(30, 'CEDEAGRO'),
(31, 'ELECTRONICA, AUTOMATIZACIÓN Y ENERGIAS RENOVABLES'),
(32, 'Grupo de Investigación en Biotecnología, Seguridad Alimentaria y Nutricional'),
(33, 'Grupo de Investigación en Recursos Naturales, Biotecnología y Bioprospección- RENABBIO'),
(34, 'Grupo de Investigación, Diseño y Desarrollo Aplicado (GRINDDA'),
(35, 'Grupo de Investigación Comercio y Servicios GRICS'),
(36, 'GIIDA Grupo de Investigación e Innovación para el Desarrollo de la Amazonía'),
(37, 'MUSSA CAFEC'),
(38, 'GRUPO DE ESTUDIOS EN INVESTIGACIÓN E INNOVACIÓN TECNOLÓGICA AGROPECUARIA GEITA'),
(39, 'Grupo de Investigación SINERGIA'),
(40, 'Innovación y desarrollo tecnológico Innovatec CTPI'),
(41, 'GRUPO DE INVESTIGACION CENTRO BIOTECNOLOGICO DEL CARIBE - BIOTEC'),
(42, 'Grupo de Investigación del SENA COMM (INVECOMM)'),
(43, 'Grupo de investigación en desarrollo empresarial, tecnologías y ciencias agrarias BIOSENA'),
(44, 'GRUPO DE INVESTIGACIÓN EN BIODIVERSIDAD, INNOVACIÓN TECNOLÓGICA Y SOSTENIBILIDAD AMBIENTAL SENA -CHOCÓ'),
(45, 'Grupo de Investigación Ciencias Ambientales Aplicadas \"GICAP\"'),
(46, 'GRUPO DE INVESTIGACIÓN COMERCIO, INDUSTRIA Y TURISMO-GICIT'),
(47, 'INVESTIGACIONES CABP'),
(48, 'IDICAEF'),
(49, 'GRUPO DE INVESTIGACIÓN EN INNOVACIÓN AGROINDUSTRIAL Y PRODUCCIÓN SOSTENIBLE'),
(50, 'CIDEINNOVA'),
(51, 'CIBA-CBA'),
(52, 'TECNOLOGÍA Y PRODUCTIVIDAD'),
(53, 'Grupo de Investigación en Tecnologías Aplicadas Empresariales GITAE'),
(54, 'GICS - Grupo de Investigación del CEET SENA'),
(55, 'INNMODA-CMTC'),
(56, 'Grupo de Investigación en Actividad Física y Deporte SENA Bogotá'),
(57, 'GRUPO DE INVESTIGACIÓN EN PROCESOS INDUSTRIALES SENA CGI'),
(58, 'SUOMAYA CGMLTI SENA'),
(59, 'Formación en Tecnologías y Sistemas de Transporte-CTT (FORTECTT)'),
(60, 'Ingraf'),
(61, 'Grupo de Investigación Desarrollo e Innovación del Sector Financiero GIDiSF'),
(62, 'Grupo de Investigación del Centro de Gestión Administrativa - GICGA'),
(63, 'RECETAS, FORMULAS Y TURISMO'),
(64, 'CTCM SENA Bogotá'),
(65, 'Grupo de investigacion del Centro de Materiales y Ensayos SENA GIMES'),
(66, 'Grupo de Investigación, Desarrollo Tecnológico e Innovación del Centro de Diseño y Metrología de la Regional D.C. (GIDIME)'),
(67, 'GICEMET'),
(68, 'GISS Grupo de Investigaciónes de Servicios a la Salud'),
(69, 'Tecnova'),
(70, 'INNOVA Y EMPRENDE CAA'),
(71, 'Grupo de Investigación del Nororiente Amazónico'),
(72, 'BIOGIGAS GUAVIARE'),
(73, 'YAMBORÓ'),
(74, 'Grupo de Investigación para el Desarrollo Social y Tecnológico, Regional - Huila'),
(75, 'Grupo de investigación agroindustrial La Angostura'),
(76, 'INNOVAGRO C.A.D.P.H'),
(77, 'Grupo de Investigación Nova'),
(78, 'Innovadores Logísticos y Ecoturísticos del Magdalena'),
(79, 'ProAgroIndustria del Magdalena'),
(80, 'CISMTECH'),
(81, 'GRUINVCAM - Grupo de Investigación Centro Agroindustrial del Meta'),
(82, 'LOPEINVESTIGACIONES'),
(83, 'Investigación Desarrollo Emprendimiento y Aprendizaje-IDEA'),
(84, 'TUMACO DIVERSO'),
(85, 'GINDET (Grupo de Investigación en Desarrollo Tecnológico e Innovación)'),
(86, 'CEDRUM NDS'),
(87, 'Grupo de investigación Arapaima'),
(88, 'SENAGROQUIN'),
(89, 'CREAMÁS'),
(90, 'GIDA - CDTCI'),
(91, 'Merkator'),
(92, 'Grupo de investigación en Ciencias Agropecuarias ICATURS'),
(93, 'TEINNOVA CDITI'),
(94, 'Seaflower Investigation Group-Sena San Andres'),
(95, 'FRAILEJONES'),
(96, 'EINSTEIN'),
(97, 'GITIP-MB (Grupo de Investigación en Tecnología, Innovación y Pedagogía - Manuela Beltrán)'),
(98, 'Sena, investigaciones y desarrollos industriales aplicados- I+Dea'),
(99, 'INVESTIGADORES CGAO'),
(100, 'Grupo de Investigación en Diseño, Manufactura, Construcción, TIC y Afines - VESTIGIUM'),
(101, 'GIACIDT Grupo de Investigación Aplicada del Centro Industrial y del Desarrollo Tecnológico Barrancabermeja'),
(102, 'Grupo de Investigación y Desarrollo del Cacao y la Chocolatería'),
(103, 'INVESTIGADORES SUCREÑOS'),
(104, 'GRUPO DE INVESTIGACIÓN, DESARROLLO E INNOVACIÓN TECNOLOGICA DEL SENA REGIONAL TOLIMA - GIDIS'),
(105, 'SENAGROTIC - Grupo de Ciencia, Tecnología e Innovación del Centro Agropecuario La Granja'),
(106, 'Grupo de Investigación en Gestion Empresarial, Servicios e Innovación Comercial-GESICOM'),
(107, 'GIDEMP'),
(108, 'Grupo de Investigación en Innovación, Gestión Tecnológica y del Conocimiento - INGETEC - ASTIN'),
(109, 'Unidad de Investigación Aplicada, Desarrollo Tecnologico e Innovacion, UIADTI - CEAI - SENA'),
(110, 'Grupo de Investigaciones en Ciencias & Tecnologías Agroindustriales GICTACAB'),
(111, 'Gestión Tecnológica de Servicios'),
(112, 'INNOVACLEM-INNOVACION Y DESARROLLO TECNOLOGICO DEL CLEM'),
(113, 'Grupo de Investigación e Innovación en Biotecnología - BITI'),
(114, 'Diseño y Desarrollo de Tecnologías Para la Industria y la Formación Profesional Integral - DIDETIF'),
(115, 'Investigación Tecnológica Aplicada ITA'),
(116, 'TECNOLOGÍAS PARA LA INNOVACIÓN EN CONSTRUCCIÓN (TPIC)'),
(117, 'Evolucion, Innovacion Valle Tecnologico (E-Innvatec)'),
(118, 'Grupo de Investigación para la Innovación Ambiental e Intercultural MAHIE - KtRIYAMI'),
(119, 'Grupo de Investigación Agroambiental del Vichada- GRIAV');


INSERT INTO `app_redes_conocimiento` (`id`, `nombre`) VALUES
(1, 'Red de Cultura'),
(2, 'Red de Artesanías'),
(3, 'Red de Artes gráficas'),
(4, 'Red de Comercio y ventas'),
(5, 'Red de Gestión administrativa y financiera'),
(6, 'Red de Mecánica industrial'),
(7, 'Red de Energía eléctrica'),
(8, 'Red de Electrónica y automatización'),
(9, 'Red de Telecomunicaciones'),
(10, 'Red de Química aplicada'),
(11, 'Red de Informática, diseño y desarrollo de software'),
(12, 'Red Automotor'),
(13, 'Red Aeroespacial'),
(14, 'Red Textil, confección, diseño y moda'),
(15, 'Red de Cuero, calzado y marroquinería'),
(16, 'Red de Materiales para la industria'),
(17, 'Red de Minería'),
(18, 'Red de Hidrocarburos'),
(19, 'Red de Logística y gestión de la producción'),
(20, 'Red de Construcción'),
(21, 'Red de Infraestructura'),
(22, 'Red Agrícola'),
(23, 'Red Pecuaria'),
(24, 'Red Acuícola y de pesca'),
(25, 'Red Ambiental'),
(26, 'Red de Biotecnología'),
(27, 'Red de Salud'),
(28, 'Red de Hotelería y turismo'),
(29, 'Red de Actividad física, recreación y deporte'),
(30, 'Red de Transporte'),
(31, 'Red de Servicios personales');


INSERT INTO `app_roles` (`id`, `rol`) VALUES
(1, 'L'),
(2, 'F'),
(3, 'E'),
(4, 'Admin');


INSERT INTO `app_subareas_conocimiento` (`id`, `nombre`) VALUES
(1, 'Matemática'),
(2, 'Computación y ciencias de la información'),
(3, 'Ciencias físicas'),
(4, 'Ciencias químicas'),
(5, 'Ciencias de la tierra y medioambiente'),
(6, 'Ciencias biológicas'),
(7, 'Biotecnología, microbiología y biodiversidad'),
(8, 'Otras ciencias naturales'),
(9, 'Nanotecnología'),
(10, 'Ingeniería civil'),
(11, 'Ingeniería petróleos, minas, geología'),
(12, 'Ingeniería eléctrica, electrónica, automatización y energías alternativas'),
(13, 'Ingeniería mecánica'),
(14, 'Ingeniería de sistemas'),
(15, 'Ingeniería Química'),
(16, 'Ingeniería de materiales'),
(17, 'Ingeniería médica'),
(18, 'Ingeniería ambiental'),
(19, 'Ingeniería Industrial'),
(20, 'Diseño industrial'),
(21, 'Agroindustria'),
(22, 'Inteligencia artificial'),
(23, 'Internet de las cosas IoT'),
(24, 'Analítica de datos'),
(25, 'Big Data'),
(26, 'Transformación Digital'),
(27, 'Medicina básica'),
(28, 'Ciencias de la salud'),
(29, 'Biotecnología en salud'),
(30, 'Otras ciencias médicas (forense, fonaudiología)'),
(31, 'Agricultura, agronomía'),
(32, 'Biotecnología vegetal'),
(33, 'Agrícola'),
(34, 'Silvicultura y pesca'),
(35, 'Pecuaria, ciencias animales y lechería'),
(36, 'Biotecnología animal'),
(37, 'Psicología'),
(38, 'Economía y negocios'),
(39, 'Ciencias de la educación'),
(40, 'Sociología'),
(41, 'Derecho'),
(42, 'Ciencias políticas'),
(43, 'Geografía social y económica'),
(44, 'Periodismo y comunicaciones'),
(45, 'Otras ciencias sociales'),
(46, 'Historia y arqueología'),
(47, 'Idiomas y literatura'),
(48, 'Otras historias'),
(49, 'Arte'),
(50, 'Otras humanidades'),
(51, 'Artes y patrimonio'),
(52, 'Industrias culturales'),
(53, 'Creaciones funcionales');