INSERT INTO `app_listas_plegables` (`id`, `codigos_grupo_investigacion`, `nombre_grupo_investigacion`, `redes_conocimiento`, `subareas_conocimiento`, `diciplina_subarea`,  `nombre_centro_formacion`, `actividades_economicas`) VALUES
(1, 'COL0153676', 'ARARA', 'Red de Cultura.', ' Matemática', 'Matemáticas puras', '9517-Centro para la Biodiversidad y el Turismo del Amazonas', 'Agricultura, ganadería, caza y actividades de servicios conexas '),
(2, 'COL0085647', 'Grupo de Investigación La Salada CILS', 'Red de Artesanías.', ' Computación y ciencias de la información', 'Matemáticas aplicadas', '9101-Centro de los Recursos Naturales Renovables -La Salada', 'Silvicultura y extracción de madera'),
(3, 'COL0106783', 'Grupo de Investigación en Innovación y Agroindustria (GIIA)', 'Red de Artes gráficas.', ' Ciencias físicas', 'Estadística y probabilidades(investigacion en metodologías)', '9201-Centro del Diseño y Manufactura del Cuero', 'Pesca y acuicultura'),
(4, 'COL0110481', 'Gestión de la Innovación y el Desarrollo Tecnológico GIDT', 'Red de Comercio y ventas.', ' ciencias químicas', 'Ciencias de la Computación', '9202-Centro de Formación en Diseño, Confección y Moda.', 'Extracción de carbón de piedra y lignito'),
(5, 'COL0113017', 'GACIPE (Grupo de Investigacacion en Automatizacion,Comunicaciones Industriales , Pedagogia y Energias Alternativas)', 'Red de Gestión administrativa y financiera.', ' Ciencias de la tierra y medioambiente', 'Ciencias de la Información y Bioinformática', '9203-Centro para el Desarrollo del Hábitat y la Construcción', 'Extracción de petróleo crudo y gas natural'),
(6, 'COL0113975', 'Materiales para el Mobiliario - MATERMOB', 'Red de Mecánica industrial.', ' Ciencias biológicas', 'Física Atómica, Molecular y Química', '9204-Centro de Tecnología de la Manufactura Avanzada.', 'Extracción de minerales metalíferos'),
(7, 'COL0129409', 'BIOMATIC (Biomecánica, materiales, TICS, diseño y calidad para el sector cuero, plástico y caucho y sus cadenas productivas', 'Red de Energía eléctrica.', ' Biotecnología, microbiología y biodiversidad', 'Física de la Materia', '9205-Centro Tecnológico del Mobiliario', 'Extracción de otras minas y canteras'),
(8, 'COL0131024', 'GIGAT-Grupo de Investigación en gerencia y aplicación de la ciencia y la Tecnología', 'Red de Electrónica y automatización.', ' Otras ciencias naturales', 'Física de Partículas y Campos', '9206-Centro Textil y de Gestión Industrial', 'Actividades de servicios de apoyo para la explotación de minas '),
(9, 'COL0133799', 'Ciencia, Investigación, Conocimiento, Aprendizaje y Sociedad (CICAS)', 'Red de Telecomunicaciones.', ' Nanotecnología', 'Física Nuclear', '9301-Centro de Comercio', 'Elaboración de productos alimenticios'),
(10, 'COL0146626', 'GRUPO DE INVESTIGACIÓN, INNOVACIÓN Y DESARROLLO PARA LA SUBREGIÓN DEL URABÁ- ABIBE', 'Red de Química aplicada.', ' Ingeniería civil', 'Física de Plasmas y Fluídos', '9401-Centro de Servicios de Salud', 'Elaboración de bebidas'),
(11, 'COL0149529', 'GIDOCA', 'Red de Informática, diseño y desarrollo de software.', ' Ingeniería petróleos, minas, geología.', 'Óptica', '9402-Centro de Servicios y Gestión Empresarial', 'Elaboración de productos de tabaco'),
(12, 'COL0149869', 'Grupo de Investigación red de construcción, infraestructura y servicios públicos-GIRCIS', 'Red Automotor.', ' Ingeniería eléctrica, electrónica, automatización y energías alternativas', 'Acústica', '9501-Complejo Tecnológico para la Gestión Agroempresarial', 'Fabricación de productos textiles'),
(13, 'COL0150772', 'Grupo de Investigación Ciencia, Tecnología e Innovación en Salud (CITEISA)', 'Red Aeroespacial.', ' Ingeniería mecánica', 'Astronomía', '9502-Complejo Tecnológico Minero Agroempresarial ', 'Confección de prendas de vestir'),
(14, 'COL0151199', 'Grupo de Investigación aplicada a la Industria, al Textil y a la Química (GIAITEQ)', 'Red Textil, confección, diseño y moda.', ' Ingeniería de sistemas', 'Química Orgánica', '9503-Centro de la Innovación, la Agroindustria y la Aviación', 'Curtido y recurtido de cueros; fabricación de calzado; fabricación de artículos de viaje, maletas, bolsos de mano y artículos similares, y fabricación de artículos de talabartería y guarnicionería; adobo y teñido de pieles'),
(15, 'COL0158921', 'INAMOD Grupo de Investigación Aplicada en Moda y Diseño', 'Red de Cuero, calzado y marroquinería.', ' Ingeniería Química', 'Química Inorgánica y Nuclear', '9504-Complejo Tecnológico Agroindustrial, Pecuario y Turístico', 'Transformación de la madera y fabricación de productos de madera y de corcho, excepto muebles; fabricación de artículos de cestería y espartería'),
(16, 'COL0163494', 'GITECA: Grupo de Investigación Tecnológica Agropecuaria del Bajo Cauca', 'Red de Materiales para la industria.', ' Ingeniería de materiales ', 'Química Física', '9549-Complejo Tecnológico, Turístico y Agroindustrial del Occidente Antioqueño', 'Fabricación de papel, cartón y productos de papel y cartón'),
(17, 'COL0179313', 'GIMAB (Grupo de Investigación Minero Ambiental de El Bagre)', 'Red de Minería.', ' Ingeniería médica', 'Ciencias de los Polímeros', '9127-Centro de Formación Minero Ambiental', 'Actividades de impresión y de producción de copias a partir de grabaciones originales '),
(18, 'COL0160339', 'GIISATA Grupo de Investigación para la Innovación Social, Agroindustrial, Tecnológica y Ambiental Araucana', 'Red de Hidrocarburos.', ' Ingeniería ambiental', 'Electroquímica', '9530-Centro de Gestión y Desarrollo Agroindustrial de Arauca', 'Coquización, fabricación de productos de la refinación del petróleo y actividad de mezcla de combustibles '),
(19, 'COL0147712', 'GIPAMA - Mejoramiento de la Producción Primaria, Agroindustria y Medio Ambiente', 'Red de Logística y gestión de la producción.', ' Ingeniería Industrial', 'Química de los Coloides', '9103-Centro para el Desarrollo Agroecologico y Agroindustrial', 'Fabricación de sustancias y productos químicos'),
(20, 'COL0147991', 'Arcadia', 'Red de Construcción.', ' Diseño industrial', 'Química Analítica', '9207-Centro Nacional Colombo Alemán', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico'),
(21, 'COL0148246', 'CNCA', 'Red de Infraestructura.', ' Agroindustria', 'Geociencias (Multidisciplinario)', '9208-Centro Industrial y de Aviación  ', 'Fabricación de productos de caucho y de plástico'),
(22, 'COL0148273', 'Grupo de Investigación del Centro Industrial y de Aviación (GICI)', 'Red Agrícola.', ' Inteligencia artificial', 'Mineralogía', '9302-Centro de Comercio y Servicios', 'Fabricación de otros productos minerales no metálicos'),
(23, 'COL0116654', 'Grupo de Investigación en Procesos de la Industria Petroquímica "GIPIPQ"', 'Red Pecuaria.', ' Internet de las cosas IoT', 'Paleontología', '9104-Centro Agroempresarial y Minero', 'Fabricación de productos metalúrgicos básicos'),
(24, 'COL0150389', 'GIBIOMAS', 'Red Acuícola y de pesca.', ' Analítica de datos', 'Geoquímica y Geofísica', '9105-Centro Internacional Náutico, Fluvial y Portuario', 'Fabricación de productos elaborados de metal, excepto maquinaria y equipo'),
(25, 'COL0152427', 'SENA CINAFLUP', 'Red Ambiental.', ' Big Data', 'Geografía Física', '9218-Centro para la Industria Petroquímica', 'Fabricación de productos informáticos, electrónicos y ópticos'),
(26, 'COL0152739', 'GRUPO DE INVESTIGACION BIOTECNOLOGÍA E INNOVACIÓN (GIBEI)', 'Red de Biotecnología.', ' Transformación Digital', 'Geología', '9304-Centro de Comercio y Servicios', 'Fabricación de aparatos y equipo eléctrico'),
(27, 'COL0152937', 'GRUPO DE INVESTIGACIÓN , INNOVACIÓN Y CONOCIMIENTO APLICADO DE BOYACÁ GICAB', 'Red de Salud.', ' Medicina básica', 'Vulcanología', '9110-Centro de Desarrollo Agropecuario y Agroindustrial ', 'Fabricación de maquinaria y equipo n.c.p.'),
(28, 'COL0157352', 'GICEMIN', 'Red de Hotelería y turismo.', ' Ciencias de la salud', 'Ciencias del Medio Ambiente', '9111-Centro  Minero', 'Fabricación de vehículos automotores, remolques y semirremolques'),
(29, 'COL0158019', 'GRUPO DE INVESTIGACIÓN, INNOVACIÓN, DESARROLLO SOCIAL, EMPRESARIAL Y TECNOLÓGICO', 'Red de Actividad física, recreación y deporte.', ' Biotecnología en salud', 'Meteorología y Ciencias Atmosféricas', '9305-Centro de Gestión Administrativa y Fortalecimiento Empresarial ', 'Fabricación de otros tipos de equipo de transporte'),
(30, 'COL0162236', 'CEDEAGRO', 'Red de Transporte.', ' Otras ciencias médicas (forense, fonaudiología)', 'Investigación del Clima', '9514-Centro Industrial de Mantenimiento y Manufactura', 'Fabricación de muebles, colchones y somieres'),
(31, 'COL0102695', 'ELECTRONICA, AUTOMATIZACIÓN Y ENERGIAS RENOVABLES', 'Red de Servicios personales.', ' Agricultura, agronomía', 'Oceanografía, Hidrología y Recursos del Agua', '9112-Centro para la Formación Cafetera', 'Otras industrias manufactureras'),
(32, 'COL0129797', 'Grupo de Investigación en Biotecnología, Seguridad Alimentaria y Nutricional', '', ' Biotecnología vegetal', 'Métodos de Investigación en Bioquímica', '9219-Centro de Automatización Industrial', 'Instalación, mantenimiento y reparación especializado de maquinaria y equipo'),
(33, 'COL0135328', 'Grupo de Investigación en Recursos Naturales, Biotecnología y Bioprospección- RENABBIO', '', ' Agrícola', 'Biofísica', '9220-Centro de Procesos Industriales y Construcción', 'Suministro de electricidad, gas, vapor y aire acondicionado '),
(34, 'COL0153193', 'Grupo de Investigación, Diseño y Desarrollo Aplicado (GRINDDA)', '', ' Silvicultura y pesca', 'Genética y Herencia', '9306-Centro de Comercio y Servicios', 'Captación, tratamiento y distribución de agua'),
(35, 'COL0154978', 'Grupo de Investigación Comercio y Servicios GRICS', '', ' Pecuaria, ciencias animales y lechería', 'Biología Reproductiva', '9515-Centro Pecuario y Agroempresarial', 'Evacuación y tratamiento de aguas residuales'),
(36, 'COL0161426', 'GIIDA Grupo de Investigación e Innovación para el Desarrollo de la Amazonía', '', ' Biotecnología animal', 'Biología del Desarrollo', '9516-Centro Tecnológico de la Amazonia', 'Recolección, tratamiento y disposición de desechos, recuperación de materiales'),
(37, 'COL0160536', 'MUSSA CAFEC', '', ' Psicología', 'Botánica y Ciencias de las Plantas', '9519-Centro Agroindustrial y Fortalecimiento Empresarial de Casanare', 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos'),
(38, 'COL0149369', 'GRUPO DE ESTUDIOS EN INVESTIGACIÓN E INNOVACIÓN TECNOLÓGICA AGROPECUARIA GEITA', '', ' Economía y negocios', 'Zoología, Ornitología, Entomología, Ciencias Biológicas del Comportamiento', '9113-Centro Agropecuario', 'Construcción de edificios'),
(39, 'COL0150487', 'Grupo de Investigación SINERGIA', '', ' Ciencias de la educación', 'Biología Marina y del Agua', '9221-Centro de Teleinformática y Producción Industrial ', 'Obras de ingeniería civil'),
(40, 'COL0141469', 'Innovación y desarrollo tecnológico Innovatec CTPI', '', ' Sociología', 'Ecología', '9307-Centro de Comercio y Servicios', 'Actividades especializadas para la construcción de edificios y obras de ingeniería civil'),
(41, 'COL0039958', 'GRUPO DE INVESTIGACION CENTRO BIOTECNOLOGICO DEL CARIBE - BIOTEC', '', ' Derecho', 'Conservación de la Biodiversidad', '9114-Centro Biotecnológico del Caribe', 'Comercio, mantenimiento y reparación de vehículos automotores y motocicletas, sus partes, piezas y accesorios'),
(42, 'COL0149637', 'Grupo de Investigación del SENA COMM (INVECOMM)', '', ' Ciencias políticas', 'Biología (Teórica, Matemática, Criobiología, Evolutiva)', '9520-Centro Agroempresarial', 'Comercio al por mayor y en comisión o por contrata, excepto el comercio de vehículos automotores y motocicletas'),
(43, 'COL0192825', 'Grupo de investigación en desarrollo empresarial, tecnologías y ciencias agrarias BIOSENA', '', ' Geografía social y económica', 'Otras Biologías', '9521-Centro de Operación y Mantenimiento Minero', 'Comercio al por menor (incluso el comercio al por menor de combustibles), excepto el de vehículos automotores y motocicletas'),
(44, 'COL0160376', 'GRUPO DE INVESTIGACIÓN EN BIODIVERSIDAD, INNOVACIÓN TECNOLÓGICA Y SOSTENIBILIDAD AMBIENTAL SENA -CHOCÓ', '', ' Periodismo y comunicaciones', 'Biología Celular', '9522-Centro de Recursos Naturales, Industria y Biodiversidad', 'Transporte terrestre; transporte por tuberías'),
(45, 'COL0151189', 'Grupo de Investigación Ciencias Ambientales Aplicadas "GICAP"', '', ' Otras ciencias sociales', 'Bioquímica y Biología Molecular', '9115-Centro Agropecuario y de Biotecnología el Porvenir', 'Transporte acuático'),
(46, 'COL0154548', 'GRUPO DE INVESTIGACIÓN COMERCIO, INDUSTRIA Y TURISMO-GICIT', '', ' Historia y arqueología', 'Microbiología', '9523-Centro de Comercio, Industria y Turismo de Córdoba', 'Transporte aéreo'),
(47, 'COL0157577', 'INVESTIGACIONES CABP', '', ' Idiomas y literatura', 'Virología', '9232-Centro Industrial y de Desarrollo Empresarial de Soacha', 'Almacenamiento y actividades complementarias al transporte'),
(48, 'COL0138544', 'IDICAEF', '', ' Otras historias', 'Micología', '9509-Centro de Desarrollo Agroindustrial y Empresarial', 'Correo y servicios de mensajería'),
(49, 'COL0144004', 'GRUPO DE INVESTIGACIÓN EN INNOVACIÓN AGROINDUSTRIAL Y PRODUCCIÓN SOSTENIBLE', '', ' Arte', 'Biotecnología Medioambiental', '9510-Centro Agroecológico y Empresarial ', 'Alojamiento'),
(50, 'COL0150244', 'CIDEINNOVA', '', ' Otras humanidades', 'Bioremediación, biotecnología para el diagnóstico (chips ADN y biosensores) en manejo ambiental', '9511-Centro de la Tecnología de Diseño y la Productividad Empresarial', 'Actividades de servicios de comidas y bebidas'),
(51, 'COL0160438', 'CIBA-CBA', '', ' Artes y patrimonio', 'Ética relacionada con Biotecnología Medioambiental', '9512-Centro de Biotecnología Agropecuaria', 'Actividades de edición'),
(52, 'COL0164025', 'TECNOLOGÍA Y PRODUCTIVIDAD', '', 'Industrias culturales', 'Biotecnología Industrial', '9513-Centro de Desarrollo Agroempresarial ', 'Actividades cinematográficas, de video y producción de programas de televisión, grabación de sonido y edición de música'),
(53, 'COL0166807', 'Grupo de Investigación en Tecnologías Aplicadas Empresariales GITAE', '', 'Creaciones funcionales ', 'Tecnologías de Bioprocesamiento, Biocatálisis, Fermentación', '9209-Centro de Tecnologías para la Construcción y la Madera', 'Actividades de programación, transmisión y/o difusión'),
(54, 'COL0133996', 'GICS - Grupo de Investigación del CEET SENA', '', '', 'Bioproductos (productos que se manufacturan usando biotecnología), biomateriales, bioplásticos, biocombustibles, materiales nuevos bioderivados, químicos finos bioderivados', '9210-Centro de Electricidad, Electrónica y Telecomunicaciones', 'Telecomunicaciones'),
(55, 'COL0146223', 'INNMODA-CMTC', '', '', 'Otras Ciencias Naturales', '9211-Centro de Gestión Industrial', 'Desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas), consultoría informática y actividades relacionadas'),
(56, 'COL0148068', 'Grupo de Investigación en Actividad Física y Deporte SENA Bogotá', '', '', 'Nanomateriales (producción y propiedades)', '9212-Centro de Manufactura en Textil y Cuero', 'Actividades de servicios de información'),
(57, 'COL0149305', 'GRUPO DE INVESTIGACIÓN EN PROCESOS INDUSTRIALES SENA CGI', '', '', 'Nanoprocesos (aplicaciones a nanoescala)', '9213-Centro de Tecnologías del Transporte', 'Actividades de servicios financieros, excepto las de seguros y de pensiones'),
(58, 'COL0150478', 'SUOMAYA CGMLTI SENA', '', '', 'Ingeniería Civil', '9214-Centro Metalmecánico', 'Seguros (incluso el reaseguro), seguros sociales y fondos de pensiones, excepto la seguridad social'),
(59, 'COL0150899', 'Formación en Tecnologías y Sistemas de Transporte-CTT (FORTECTT)', '', '', 'Ingeniería Arquitectónica', '9215-Centro de Materiales y Ensayos', 'Actividades auxiliares de las actividades de servicios financieros'),
(60, 'COL0152356', 'Ingraf', '', '', 'Ingeniería de la Construcción', '9216-Centro de Diseño y Metrología', 'Actividades inmobiliarias'),
(61, 'COL0154539', 'Grupo de Investigación Desarrollo e Innovación del Sector Financiero GIDiSF', '', '', 'Ingeniería Estructural y Municipal', '9217-Centro para la Industria de la Comunicación Grafica', 'Actividades jurídicas y de contabilidad'),
(62, 'COL0157835', 'Grupo de Investigación del Centro de Gestión Administrativa - GICGA', '', '', 'Ingeniería del Transporte', '9303-Centro de Gestión de Mercados, Logística y Tecnologías de la Información', 'Actividades de administración empresarial; actividades de consultoría de gestión'),
(63, 'COL0158663', 'RECETAS, FORMULAS Y TURISMO', '', '', 'Ingeniería petróleos, minas, geología.', '9403-Centro de Formación de Talento Humano en Salud', 'Actividades de arquitectura e ingeniería; ensayos y análisis técnicos'),
(64, 'COL0160287', 'CTCM SENA Bogotá', '', '', 'Ingeniería Eléctrica y Electrónica', '9404-Centro de Gestión Administrativa', 'Investigación científica y desarrollo'),
(65, 'COL0160607', 'Grupo de investigacion del Centro de Materiales y Ensayos SENA GIMES', '', '', 'Robótica y Control Automático', '9405-Centro de Servicios Financieros', 'Publicidad y estudios de mercado'),
(66, 'COL0160616', 'Grupo de Investigación, Desarrollo Tecnológico e Innovación del Centro de Diseño y Metrología de la Regional D.C. (GIDIME)', '', '', 'Automatización y Sistemas de Control', '9406-Centro Nacional de Hoteleria, Turismo y Alimentos', 'Otras actividades profesionales, científicas y técnicas'),
(67, 'COL0162871', 'GICEMET', '', '', 'Energías alternativas', '9508-Centro de Formación en Actividad Física y cultura', 'Actividades veterinarias'),
(68, 'COL0163529', 'GISS Grupo de Investigaciónes de Servicios a la Salud', '', '', 'Ingeniería Mecánica', '9547-Centro Ambiental y Ecoturistico del Nororiente Amazónico', 'Actividades de alquiler y arrendamiento'),
(69, 'COL0147276', 'Tecnova', '', '', 'Mecánica Aplicada', '9222-Centro Industrial y de Energías Alternativas', 'Actividades de empleo'),
(70, 'COL0153719', 'INNOVA Y EMPRENDE CAA', '', '', 'Termodinámica', '9524-Centro Agroempresarial y Acuícola', 'Actividades de las agencias de viajes, operadores turísticos, servicios de reserva y actividades relacionadas'),
(71, 'COL0182408', 'Grupo de Investigación del Nororiente Amazónico', '', '', 'Ingeniería Aeroespacial', '9533-Centro de Desarrollo Agroindustrial, Turístico y Tecnológico del Guaviare', 'Actividades de seguridad e investigación privada'),
(72, 'COL0151018', 'BIOGIGAS GUAVIARE', '', '', 'Ingeniería Nuclear', '9116-Centro de Formación Agroindustrial', 'Actividades de servicios a edificios y paisajismo (jardines, zonas verdes)'),
(73, 'COL0039288', 'YAMBORÓ', '', '', 'Ingeniería del Audio', '9525-Centro Agroempresarial y Desarrollo Pecuario del Huila', 'Actividades administrativas y de apoyo de oficina y otras actividades de apoyo a las empresas'),
(74, 'COL0149439', 'Grupo de Investigación para el Desarrollo Social y Tecnológico, Regional - Huila', '', '', 'Ingeniería de Sistemas y Comunicaciones', '9526-Centro de Desarrollo Agroempresarial y Turístico del Huila', 'Administración pública y defensa; planes de seguridad social de afiliación obligatoria'),
(75, 'COL0149468', 'Grupo de investigación agroindustrial La Angostura', '', '', 'Telecomunicaciones', '9527-Centro de la Industria, la Empresa y los Servicios', 'Educación'),
(76, 'COL0150674', 'INNOVAGRO C.A.D.P.H', '', '', 'Hardware y Arquitectura de Computadores', '9528-Centro de Gestión y Desarrollo Sostenible Surcolombiano', 'Actividades de atención de la salud humana'),
(77, 'COL0164713', 'Grupo de Investigación Nova', '', '', 'Ingeniería Química (Plantas y Productos)', '9118-Centro Acuícola y Agroindustrial de Gaira', 'Actividades de atención residencial medicalizada'),
(78, 'COL0155376', 'Innovadores Logísticos y Ecoturísticos del Magdalena', '', '', 'Ingeniería de Procesos', '9529-Centro de Logística y Promoción Ecoturística del Magdalena', 'Actividades de asistencia social sin alojamiento'),
(79, 'COL0157737', 'ProAgroIndustria del Magdalena', '', '', 'Ingeniería Mecánica', '9117-Centro Agroindustrial del Meta', 'Actividades creativas, artísticas y de entretenimiento'),
(80, 'COL0110285', 'CISMTECH', '', '', 'Cerámicos', '9532-Centro de Industria y Servicios del Meta', 'Actividades de bibliotecas, archivos, museos y otras actividades culturales'),
(81, 'COL0156739', 'GRUINVCAM - Grupo de Investigación Centro Agroindustrial del Meta', '', '', 'Recubrimientos y películas', '9534-Centro Sur Colombiano de Logística Internacional', 'Actividades de juegos de azar y apuestas'),
(82, 'COL0150057', 'LOPEINVESTIGACIONES', '', '', 'Compuestos (Laminados, Plásticos Reforzados, Fibras Sintéticas y Naturales, etc.)', '9535-Centro Agroindustrial y Pesquero de la Costa Pacifica', 'Actividades deportivas y actividades recreativas y de esparcimiento'),
(83, 'COL0157906', 'Investigación Desarrollo Emprendimiento y Aprendizaje-IDEA', '', '', 'Papel y Madera', '9536-Centro Internacional de Producción Limpia - Lope', 'Actividades de asociaciones'),
(84, 'COL0192754', 'TUMACO DIVERSO', '', '', 'Textiles', '9119-Centro de Formación para el Desarrollo Rural y Minero', 'Mantenimiento y reparación de computadores, efectos personales y enseres domésticos'),
(85, 'COL0160679', 'GINDET (Grupo de Investigación en Desarrollo Tecnológico e Innovación)', '', '', 'Ingeniería Médica', '9537-Centro de la Industria, la Empresa y los Servicios', 'Otras actividades de servicios personales'),
(86, 'COL0171834', 'CEDRUM NDS', '', '', 'Tecnología médica de laboratorio (análisis de muestras, tecnologías para el diagnóstico)', '9518-Centro Agroforestal y Acuícola Arapaima', 'Actividades de los hogares individuales como empleadores de personal doméstico'),
(87, 'COL0153709', 'Grupo de investigación Arapaima', '', '', 'Ingeniería Ambiental y Geológica e', '9120-Centro Agroindustrial', 'Actividades no diferenciadas de los hogares individuales como productores de bienes y servicios para uso propio'),
(88, 'COL0117491', 'SENAGROQUIN', '', '', 'Geotécnicas', '9231-Centro para el Desarrollo Tecnológico de la Construcción y la Industria', 'Actividades de organizaciones y entidades extraterritoriales'),
(89, 'COL0149628', 'CREAMÁS', '', '', 'Ingeniería del Petróleo (Combustibles, Aceites), Energía y Combustibles', '9538-Centro de Comercio y Turismo', ''),
(90, 'COL0153433', 'GIDA - CDTCI', '', '', 'Sensores Remotos', '9121-Centro Atención Sector Agropecuario', ''),
(91, 'COL0149566', 'Merkator', '', '', 'Minería y Procesamiento de Minerales', '9223-Centro de Diseño e Innovación Tecnológica Industrial', ''),
(92, 'COL0153291', 'Grupo de investigación en Ciencias Agropecuarias ICATURS', '', '', 'Ingeniería Marina, Naves', '9308-Centro de Comercio y Servicios', ''),
(93, 'COL0163609', 'TEINNOVA CDITI', '', '', 'Ingeniería Oceanográfica', '9539-Centro de Formación Turística, Gente de Mar y de Servicios', ''),
(94, 'COL0156149', 'Seaflower Investigation Group-Sena San Andres', '', '', 'Logística', '9122-Centro Atención Sector Agropecuario', ''),
(95, 'COL0056672', 'FRAILEJONES', '', '', 'Ingeniería de Producción', '9224-Centro Industrial de Mantenimiento Integral', ''),
(96, 'COL0133029', 'EINSTEIN', '', '', 'Ingeniería Industrial', '9225-Centro Industrial del Diseño y la Manufactura', ''),
(97, 'COL0135139', 'GITIP-MB (Grupo de Investigación en Tecnología, Innovación y Pedagogía - Manuela Beltrán)', '', '', ' Diseño industrial', '9309-Centro de Servicios Empresariales y Turísticos', ''),
(98, 'COL0149501', 'Sena, investigaciones y desarrollos industriales aplicados- I+Dea', '', '', 'Agroindustria alimentaria', '9540-Centro Industrial y del Desarrollo Tecnológico', ''),
(99, 'COL0150932', 'INVESTIGADORES CGAO', '', '', 'Agroindustria no alimentaria', '9541-Centro Agroturístico', ''),
(100, 'COL0152098', 'Grupo de Investigación en Diseño, Manufactura, Construcción, TIC y Afines - VESTIGIUM', '', '', 'Alimentos y Bebidas', '9545-Centro Agroempresarial y Turístico de los Andes', ''),
(101, 'COL0154486', 'GIACIDT Grupo de Investigación Aplicada del Centro Industrial y del Desarrollo Tecnológico Barrancabermeja', '', '', 'Inteligencia artificial', '9546-Centro de Gestión Agroempresarial del Oriente', ''),
(102, 'COL0156462', 'Grupo de Investigación y Desarrollo del Cacao y la Chocolatería', '', '', ' Internet de las cosas IoT', '9542-Centro de la Innovación, la Tecnología y los Servicios', ''),
(103, 'COL0155044', 'INVESTIGADORES SUCREÑOS', '', '', 'Analítica de datos', '9123-Centro Agropecuario la Granja', ''),
(104, 'COL0112154', 'GRUPO DE INVESTIGACIÓN, DESARROLLO E INNOVACIÓN TECNOLOGICA DEL SENA REGIONAL TOLIMA - GIDIS', '', '', 'Big Data', '9226-Centro de Industria y Construcción', ''),
(105, 'COL0149225', 'SENAGROTIC - Grupo de Ciencia, Tecnología e Innovación del Centro Agropecuario La Granja', '', '', 'Transformación Digital', '9310-Centro de Comercio y Servicios', ''),
(106, 'COL0149388', 'Grupo de Investigación en Gestion Empresarial, Servicios e Innovación Comercial-GESICOM', '', '', 'Anatomía y Morfología', '9124-Centro Agropecuario de Buga', ''),
(107, 'COL0041052', 'GIDEMP', '', '', 'Genética humana', '9125-Centro Latinoamericano de  Especies Menores', ''),
(108, 'COL0104635', 'Grupo de Investigación en Innovación, Gestión Tecnológica y del Conocimiento - INGETEC - ASTIN', '', '', 'Inmunología', '9126-Centro Náutico Pesquero de Buenaventura', ''),
(109, 'COL0112332', 'Unidad de Investigación Aplicada, Desarrollo Tecnologico e Innovacion, UIADTI - CEAI - SENA', '', '', 'Neurociencias', '9227-Centro de Electricidad y Automatización Industrial -CEAI', ''),
(110, 'COL0125779', 'Grupo de Investigaciones en Ciencias & Tecnologías Agroindustriales GICTACAB', '', '', 'Farmacología y Farmacia', '9228-Centro de la Construcción', ''),
(111, 'COL0143188', 'Gestión Tecnológica de Servicios', '', '', 'Medicina Química', '9229-Centro de Diseño Tecnológico Industrial', ''),
(112, 'COL0149323', 'INNOVACLEM-INNOVACION Y DESARROLLO TECNOLOGICO DEL CLEM', '', '', 'Toxicología', '9230-Centro Nacional de Asistencia Técnica a la Industria -ASTIN', ''),
(113, 'COL0150745', 'Grupo de Investigación e Innovación en Biotecnología - BITI', '', '', 'Fisiología (incluye Citología)', '9311-Centro de Gestión Tecnológica de Servicios', ''),
(114, 'COL0156229', 'Diseño y Desarrollo de Tecnologías Para la Industria y la Formación Profesional Integral - DIDETIF', '', '', 'Patología', '9543-Centro de Tecnologías Agroindustriales', ''),
(115, 'COL0158699', 'Investigación Tecnológica Aplicada ITA', '', '', 'Andrología', '9544-Centro de Biotecnología Industrial', ''),
(116, 'COL0165784', 'TECNOLOGÍAS PARA LA INNOVACIÓN EN CONSTRUCCIÓN (TPIC)', '', '', 'Obstetricia y Ginecología', '9548-Centro Agropecuario y de Servicios Ambientales "Jiri-jirimo"', ''),
(117, 'COL0189276', 'Evolucion, Innovacion Valle Tecnologico (E-Innvatec)', '', '', 'Pediatría', '9531-Centro de Producción y Transformación Agroindustrial de la Orinoquia', ''),
(118, 'COL0171843', 'Grupo de Investigación para la Innovación Ambiental e Intercultural MAHIE - KtRIYAMI', '', '', 'Cardiovascular', '', ''),
(119, 'COL0164249', 'Grupo de Investigación Agroambiental del Vichada- GRIAV', '', '', 'Vascular Periférico', '', ''),
(120, '', '', '', '', 'Hematología', '', ''),
(121, '', '', '', '', 'Respiratoria', '', ''),
(122, '', '', '', '', 'Cuidado crítico y de Emergencia', '', ''),
(123, '', '', '', '', 'Anestesiología', '', ''),
(124, '', '', '', '', 'Ortopédica', '', ''),
(125, '', '', '', '', 'Cirugía', '', ''),
(126, '', '', '', '', 'Radiología, Medicina Nuclear y de imágenes', '', ''),
(127, '', '', '', '', 'Transplantes', '', ''),
(128, '', '', '', '', 'Odontología, Cirugía Oral y Medicina Oral', '', ''),
(129, '', '', '', '', 'Dermatología y Enfermedades Venéreas', '', ''),
(130, '', '', '', '', 'Alergias', '', ''),
(131, '', '', '', '', 'Reumatología', '', ''),
(132, '', '', '', '', 'Endocrinología y Metabolismo (Incluye Diabetes y Transtornos Hormonales)', '', ''),
(133, '', '', '', '', 'Gastroenterología y Hepatología', '', ''),
(134, '', '', '', '', 'Urología y nefrología', '', ''),
(135, '', '', '', '', 'Oncología', '', ''),
(136, '', '', '', '', 'Oftalmología', '', ''),
(137, '', '', '', '', 'Otorrinonaringología', '', ''),
(138, '', '', '', '', 'Psiquiatría', '', ''),
(139, '', '', '', '', 'Neurología clínica', '', ''),
(140, '', '', '', '', 'Geriatría', '', ''),
(141, '', '', '', '', 'Medicina General e Interna', '', ''),
(142, '', '', '', '', 'Otro temas de Medicina Clínica', '', ''),
(143, '', '', '', '', 'Medicina complementaria (sistemas alternativos)', '', ''),
(144, '', '', '', '', 'Ciencias del Cuidado de la Salud y Servicios (Administración de Hospitales, financiamiento)', '', ''),
(145, '', '', '', '', 'Políticas de Salud y Servicios', '', ''),
(146, '', '', '', '', 'Enfermería', '', ''),
(147, '', '', '', '', 'Nutrición y Dietas', '', ''),
(148, '', '', '', '', 'Salud Pública', '', ''),
(149, '', '', '', '', 'Medicina Tropical', '', ''),
(150, '', '', '', '', 'Parasitología', '', ''),
(151, '', '', '', '', 'Enfermedades Infecciosas', '', ''),
(152, '', '', '', '', 'Epidemiología', '', ''),
(153, '', '', '', '', 'Salud Ocupacional', '', ''),
(154, '', '', '', '', 'Ciencias del Deporte', '', ''),
(155, '', '', '', '', 'Ciencias Socio Biomédicas (Planificación Familiar, Salud Sexual, Efectos políticos y sociales de la investigación Biomédica)', '', ''),
(156, '', '', '', '', 'Ética', '', ''),
(157, '', '', '', '', 'Abuso de substancias', '', ''),
(158, '', '', '', '', 'Biotecnología relacionada con la salud', '', ''),
(159, '', '', '', '', 'Tecnologías para la manipulación de células, tejidos, Órganos o el organismo (Reproducción asistida)', '', ''),
(160, '', '', '', '', 'Tecnología para la Identificación y Funcionamiento del ADN, proteínas y encimas y como influencian la enfermedad', '', ''),
(161, '', '', '', '', 'Biomateriales (Relacionados con implantes, dispositivos, sensores)', '', ''),
(162, '', '', '', '', 'Ética relacionada con la Biomedicina', '', ''),
(163, '', '', '', '', 'Forénsicas', '', ''),
(164, '', '', '', '', 'Otras Ciencias Médicas', '', ''),
(165, '', '', '', '', 'Fonoaudiología', '', ''),
(166, '', '', '', '', 'Agricultura', '', ''),
(167, '', '', '', '', 'Forestal', '', ''),
(168, '', '', '', '', 'Pesca', '', ''),
(169, '', '', '', '', 'Ciencias del Suelo', '', ''),
(170, '', '', '', '', 'Horticultura y viticultura', '', ''),
(171, '', '', '', '', 'Agronomía', '', ''),
(172, '', '', '', '', 'Fitomejoramiento, Biotecnología', '', ''),
(173, '', '', '', '', 'Protección y nutrición de las plantas', '', ''),
(174, '', '', '', '', 'Maquinaria agrícola', '', ''),
(175, '', '', '', '', 'Pesca', '', ''),
(176, '', '', '', '', 'Pecuaria y otras', '', ''),
(177, '', '', '', '', 'Biotecnología (sembradíos y ganado), clonamiento de ganado, selección asistida, dignóstico (con chips ADN, biosensores) ', '', ''),
(178, '', '', '', '', 'Psicología (incluye relaciones hombre-máquina)', '', ''),
(179, '', '', '', '', 'Psicología (incluye terapias de aprendizaje, habla, visual y otras discapacidades físicas y mentales)', '', ''),
(180, '', '', '', '', 'Economía', '', ''),
(181, '', '', '', '', 'Econometría', '', ''),
(182, '', '', '', '', 'Relaciones Industriales', '', ''),
(183, '', '', '', '', 'Negocios y Management', '', ''),
(184, '', '', '', '', 'Educación General (Incluye Capacitación, Pedagogía)', '', ''),
(185, '', '', '', '', 'Educación Especial (Para estudiantes dotados y aquellos con dificultades de aprendizaje)', '', ''),
(186, '', '', '', '', 'Sociologia', '', ''),
(187, '', '', '', '', 'Demografía', '', ''),
(188, '', '', '', '', 'Antropología', '', ''),
(189, '', '', '', '', 'Etnología', '', ''),
(190, '', '', '', '', 'Temas especiales (Estudio de Género, Temas Sociales, Estudios de la Familia, Trabajo Social)', '', ''),
(191, '', '', '', '', 'Derecho', '', ''),
(192, '', '', '', '', 'Penal', '', ''),
(193, '', '', '', '', '"Educación General (Incluye Capacitación, Pedagogía)', '', ''),
(194, '', '', '', '', 'Educación Especial (Para estudiantes dotados y aquellos con dificultades de aprendizaje)"', '', ''),
(195, '', '', '', '', 'Ciencias Ambientales (Aspectos Sociales)', '', ''),
(196, '', '', '', '', 'Geografía Económica y Cultural', '', ''),
(197, '', '', '', '', 'Estudios Urbanos (Planificación y Desarrollo)', '', ''),
(198, '', '', '', '', 'Planificación del Transporte y Aspectos Sociales del Transporte', '', ''),
(199, '', '', '', '', 'Periodismo', '', ''),
(200, '', '', '', '', 'Ciencias de la Información (Aspectos Sociales)', '', ''),
(201, '', '', '', '', 'Bibliotecología', '', ''),
(202, '', '', '', '', 'Medios y Comunicación Social', '', ''),
(203, '', '', '', '', 'Ciencias Sociales, Interdisciplinaria', '', ''),
(204, '', '', '', '', 'Otras Ciencias Sociales', '', ''),
(205, '', '', '', '', 'Actividades de apropiación de la la ciencia, la tecnología y cultura de la innovación dirigida a la comunidad académica', '', ''),
(206, '', '', '', '', 'Historia', '', ''),
(207, '', '', '', '', 'Arqueología', '', ''),
(208, '', '', '', '', 'Estudios Generales del Lenguaje', '', ''),
(209, '', '', '', '', 'Idiomas Específicos', '', ''),
(210, '', '', '', '', 'Estudios Literarios', '', ''),
(211, '', '', '', '', 'Teoría Literaria', '', ''),
(212, '', '', '', '', 'Literatura Específica', '', ''),
(213, '', '', '', '', 'Lingüística', '', ''),
(214, '', '', '', '', 'Historia de la Ciencia y Tecnología', '', ''),
(215, '', '', '', '', 'Otras historias especializadas', '', ''),
(216, '', '', '', '', 'Arte', '', ''),
(217, '', '', '', '', 'Historia del Arte', '', ''),
(218, '', '', '', '', 'Diseño Arquitectónico', '', ''),
(219, '', '', '', '', 'Artes de la Representación (Musicología, Ciencias del Teatro, Dramaturgia)', '', ''),
(220, '', '', '', '', 'Estudios del Folclor', '', ''),
(221, '', '', '', '', 'Estudios de Cine, Radio y Televisión', '', ''),
(222, '', '', '', '', 'Arquitectura y Urbanismo', '', ''),
(223, '', '', '', '', 'Diseño Industrial y otros diseños', '', ''),
(224, '', '', '', '', 'Otras Humanidades', '', ''),
(225, '', '', '', '', 'Filosofía', '', ''),
(226, '', '', '', '', 'Teología', '', ''),
(227, '', '', '', '', ' (Artes visuales , escénicas, turismo, gastronomía, restauración, etc)', '', ''),
(228, '', '', '', '', ' (Editorial, fonográfica, audiovisual, etc)', '', ''),
(229, '', '', '', '', '(medios digitales, software, apps, animación, diseño, publicidad,, joyería , moda y diseño, etc)', '', '');



INSERT INTO `app_roles` (`id`, `rol`) VALUES
(1, 'L'),
(2, 'F'),
(3, 'E'),
(4, 'Admin');



-- Insercion de prueba en lo que Papi Gus nos da los rubros
-- Inserción en la tabla TipoRubro
INSERT INTO app_tiporubro (`id`, `descripcion`) VALUES 
(1, 'Tecnología informática'),
(2, 'Construcción'),
(3, 'Educación'),
(4, 'Salud y medicina'),
(5, 'Alimentación y gastronomía'),
(6, 'Agricultura'),
(7, 'Automotriz'),
(8, 'Turismo y viajes'),
(9, 'Finanzas y banca'),
(10, 'Medios de comunicación'),
(11, 'Energía renovable'),
(12, 'Textil y moda'),
(13, 'Entretenimiento'),
(14, 'Arte y cultura'),
(15, 'Investigación científica'),
(16, 'Inmobiliaria'),
(17, 'Industria alimentaria'),
(18, 'Transporte y logística'),
(19, 'Publicidad y marketing'),
(20, 'Servicios legales'),
(21, 'Biotecnología avanzada'),
(22, 'Robótica aplicada'),
(23, 'Realidad virtual y aumentada'),
(24, 'Exploración espacial'),
(25, 'Blockchain y criptomonedas'),
(26, 'Diseño de experiencias'),
(27, 'Inteligencia artificial ética'),
(28, 'Sostenibilidad urbana'),
(29, 'Gestión de riesgos'),
(30, 'Bioingeniería molecular');

-- Rubros asociados a los tipos de rubros
INSERT INTO app_rubro (id, tipo_id, descripcion, estado) VALUES
-- Tecnología informática
(1, 1, 'Desarrollo de software de gestión empresarial', 1),
(2, 1, 'Análisis de datos para optimización de procesos', 0),
(3, 1, 'Desarrollo de plataformas de e-learning', 1),
(4, 1, 'Consultoría en infraestructura de redes', 1),
(5, 1, 'Diseño de interfaces de usuario', 0),
(6, 1, 'Desarrollo de aplicaciones de salud móvil', 1),
(7, 1, 'Ciberseguridad para instituciones financieras', 1),
(8, 1, 'Automatización de procesos industriales', 0),
(9, 1, 'Desarrollo de juegos educativos', 1),
(10, 1, 'Integración de sistemas empresariales', 1),
(11, 1, 'Desarrollo de aplicaciones móviles avanzadas', 1),
(12, 1, 'Gestión de proyectos de tecnología', 1),
(13, 1, 'Consultoría en inteligencia artificial', 0),
(14, 1, 'Innovación en tecnología blockchain', 1),
(15, 1, 'Desarrollo de sistemas de realidad virtual', 1),
(16, 1, 'Diseño de experiencias de usuario', 1),
(17, 1, 'Investigación en computación cuántica', 0),

-- Construcción
(18, 2, 'Diseño arquitectónico sostenible', 1),
(19, 2, 'Ingeniería de estructuras para edificios', 1),
(20, 2, 'Remodelación de espacios comerciales', 0),
(21, 2, 'Construcción de viviendas eco-friendly', 1),
(22, 2, 'Restauración de patrimonio arquitectónico', 1),
(23, 2, 'Ingeniería de cimentaciones profundas', 0),
(24, 2, 'Diseño de paisajismo urbano moderno', 1),
(25, 2, 'Construcción de infraestructura vial sustentable', 1),
(26, 2, 'Gestión de proyectos de construcción', 1),
(27, 2, 'Desarrollo de proyectos inmobiliarios', 0),
(28, 2, 'Innovación en materiales de construcción', 1),
(29, 2, 'Consultoría en eficiencia energética en edificaciones', 1),
(30, 2, 'Planificación urbana y desarrollo territorial', 0),
(31, 2, 'Gestión de residuos en proyectos de construcción', 1),
(32, 2, 'Ingeniería para proyectos de puentes y túneles', 1),
(33, 2, 'Diseño de interiores personalizados', 1),

-- Educación
(34, 3, 'Formación online especializada', 1),
(35, 3, 'Capacitación corporativa avanzada', 0),
(36, 3, 'Desarrollo de programas educativos innovadores', 1),
(37, 3, 'Consultoría en metodologías de enseñanza', 1),
(38, 3, 'Educación a distancia', 0),
(39, 3, 'Diseño curricular personalizado', 1),
(40, 3, 'Evaluación y certificación educativa', 1),
(41, 3, 'Investigación en pedagogía', 1),
(42, 3, 'Plataformas de aprendizaje colaborativo', 0),
(43, 3, 'Desarrollo de contenido educativo interactivo', 1),
(44, 3, 'Programas de formación continua', 1),
(45, 3, 'Tecnologías emergentes en la educación', 0),
(46, 3, 'Consultoría en inclusión educativa', 1),
(47, 3, 'Desarrollo de habilidades socioemocionales', 1),
(48, 3, 'E-learning adaptativo', 1),
(49, 3, 'Evaluación del aprendizaje mediante IA', 1),

-- Salud y medicina
(50, 4, 'Cirugía plástica reconstructiva', 1),
(51, 4, 'Investigación en enfermedades neurodegenerativas', 0),
(52, 4, 'Telemedicina y consultas virtuales', 1),
(53, 4, 'Investigación en tratamientos oncológicos', 1),
(54, 4, 'Medicina regenerativa', 0),
(55, 4, 'Desarrollo de dispositivos médicos innovadores', 1),
(56, 4, 'Farmacología clínica', 1),
(57, 4, 'Gestión de datos médicos y sistemas de información', 1),
(58, 4, 'Medicina preventiva y salud comunitaria', 0),
(59, 4, 'Investigación en terapias genéticas', 1),
(60, 4, 'Neurociencia aplicada a la rehabilitación', 1),
(61, 4, 'Epidemiología y salud pública', 1),
(62, 4, 'Psicoterapia y bienestar mental', 1),
(63, 4, 'Biología molecular y medicina personalizada', 0),
(64, 4, 'Neurociencia cognitiva', 1),
(65, 4, 'Investigación en vacunas y enfermedades infecciosas', 1),

-- Alimentación y gastronomía
(66, 5, 'Cocina de autor', 1),
(67, 5, 'Elaboración de alimentos gourmet', 1),
(68, 5, 'Investigación en nutrición funcional', 0),
(69, 5, 'Cocina étnica fusionada', 1),
(70, 5, 'Producción de vinos artesanales', 1),
(71, 5, 'Pastelería saludable', 0),
(72, 5, 'Gastronomía molecular', 1),
(73, 5, 'Catering personalizado', 1),
(74, 5, 'Elaboración de quesos artesanales', 1),
(75, 5, 'Cocina sostenible y responsable', 0),
(76, 5, 'Diseño de menús para dietas especiales', 1),
(77, 5, 'Investigación en nuevos sabores y texturas', 1),
(78, 5, 'Gestión de restaurantes temáticos', 1),
(79, 5, 'Producción de cerveza artesanal', 0),
(80, 5, 'Desarrollo de alimentos para intolerancias alimentarias', 1),
-- Alimentación y gastronomía
(81, 5, 'Investigación en nuevos métodos de conservación de alimentos', 1),
(82, 5, 'Creación de bebidas funcionales', 0),
(83, 5, 'Cocina molecular y técnicas avanzadas', 1),
(84, 5, 'Gestión de restaurantes de alta cocina', 1),
(85, 5, 'Diseño de experiencias gastronómicas innovadoras', 0),
(86, 5, 'Cultivo de hierbas aromáticas y especias', 1),
(87, 5, 'Producción de alimentos orgánicos certificados', 1),
(88, 5, 'Elaboración de chocolates artesanales', 1),
(89, 5, 'Desarrollo de nuevos métodos de empaque', 0),
(90, 5, 'Gastronomía fusionada de diferentes culturas', 1),
(91, 5, 'Cocina saludable y nutrición balanceada', 1),
(92, 5, 'Creación de menús para eventos especiales', 1),
(93, 5, 'Elaboración de productos gourmet para regalo', 0),
(94, 5, 'Cultivo y producción de café de especialidad', 1),
(95, 5, 'Cocina experimental con ingredientes alternativos', 1),
(96, 5, 'Cocina tradicional revisitada con técnicas modernas', 1),
(97, 5, 'Desarrollo de técnicas de cocina innovadoras', 1),

-- Agricultura
(98, 6, 'Producción de hortalizas hidropónicas', 1),
(99, 6, 'Agricultura de precisión con drones', 0),
(100, 6, 'Cultivo de plantas medicinales', 1),
(101, 6, 'Gestión integrada de plagas y enfermedades', 1),
(102, 6, 'Agricultura vertical en espacios urbanos', 0),
(103, 6, 'Cosecha y producción de frutos secos', 1),
(104, 6, 'Cultivo de plantas aromáticas y su uso en gastronomía', 1),
(105, 6, 'Tecnologías para la conservación del suelo', 1),
(106, 6, 'Crianza y producción sostenible de abejas', 0),
(107, 6, 'Agricultura regenerativa y sostenible', 1),
(108, 6, 'Desarrollo de técnicas de riego eficientes', 1),
(109, 6, 'Cultivo de frutas exóticas en climas controlados', 1),
(110, 6, 'Agricultura orgánica certificada', 0),
(111, 6, 'Producción de forraje para alimentación animal', 1),
(112, 6, 'Técnicas de cultivo alternativas para zonas áridas', 1),
(113, 6, 'Gestión de cultivos y cosechas mediante IA', 1),
-- Automotriz
(114, 7, 'Desarrollo de vehículos autónomos', 1),
(115, 7, 'Fabricación de componentes electrónicos para automóviles', 0),
(116, 7, 'Ingeniería de sistemas de seguridad vehicular', 1),
(117, 7, 'Diseño de vehículos eléctricos de alto rendimiento', 1),
(118, 7, 'Mantenimiento y reparación de sistemas de transmisión', 0),
(119, 7, 'Fabricación de vehículos híbridos', 1),
(120, 7, 'Diseño de carrocerías aerodinámicas', 1),
(121, 7, 'Desarrollo de software para gestión de flotas', 1),
(122, 7, 'Investigación en nuevos materiales para automóviles', 0),
(123, 7, 'Fabricación de sistemas de propulsión avanzados', 1),
(124, 7, 'Diseño de interiores de vehículos inteligentes', 1),
(125, 7, 'Reciclaje de materiales en la industria automotriz', 1),
(126, 7, 'Desarrollo de sistemas de asistencia al conductor', 0),
(127, 7, 'Fabricación de neumáticos innovadores', 1),
(128, 7, 'Innovación en sistemas de iluminación para vehículos', 1),
(129, 7, 'Investigación en conducción autónoma y conectada', 1),

-- Turismo y viajes
(130, 8, 'Agencia de viajes especializada en ecoturismo', 1),
(131, 8, 'Organización de viajes gastronómicos', 0),
(132, 8, 'Turismo de aventura y actividades al aire libre', 1),
(133, 8, 'Desarrollo de destinos turísticos sostenibles', 1),
(134, 8, 'Turismo cultural y rutas patrimoniales', 0),
(135, 8, 'Agencia de viajes para experiencias de lujo', 1),
(136, 8, 'Turismo médico y bienestar', 1),
(137, 8, 'Agencia de viajes para eventos deportivos', 1),
(138, 8, 'Turismo rural y agroturismo', 0),
(139, 8, 'Turismo de cruceros y navegación', 1),
(140, 8, 'Organización de viajes para avistamiento de fauna', 1),
(141, 8, 'Desarrollo de destinos turísticos innovadores', 1),
(142, 8, 'Turismo religioso y de peregrinación', 0),
(143, 8, 'Agencia de viajes para viajes en familia', 1),
(144, 8, 'Turismo de negocios y convenciones', 1),
(145, 8, 'Desarrollo de experiencias turísticas personalizadas', 1),
(167, 10, 'Desarrollo de narrativas transmedia', 1),
(168, 10, 'Producción de documentales y reportajes', 1),
(169, 10, 'Periodismo científico y divulgación', 1),
(170, 10, 'Agencia de noticias y cobertura informativa', 0),
(171, 10, 'Marketing de influencers y estrategias digitales', 1),
(172, 10, 'Creación de contenido publicitario creativo', 1),
(173, 10, 'Producción de contenido para realidad virtual', 1),
(174, 10, 'Diseño de campañas de marketing experiencial', 0),
(175, 10, 'Periodismo deportivo y eventos en vivo', 1),
(176, 10, 'Desarrollo de plataformas de comunicación interna', 1),
(177, 10, 'Consultoría en estrategias de comunicación corporativa', 1),
-- Energía renovable
(178, 11, 'Desarrollo de parques eólicos marinos', 1),
(179, 11, 'Investigación en almacenamiento de energía', 0),
(180, 11, 'Ingeniería de sistemas solares fotovoltaicos', 1),
(181, 11, 'Biocombustibles y energía a partir de residuos', 1),
(182, 11, 'Desarrollo de sistemas de energía geotérmica', 0),
(183, 11, 'Consultoría en eficiencia energética', 1),
(184, 11, 'Energía mareomotriz y de las corrientes marinas', 1),
(185, 11, 'Innovación en redes inteligentes de distribución', 1),
(186, 11, 'Desarrollo de proyectos de energía hidroeléctrica', 0),
(187, 11, 'Investigación en nuevas tecnologías de energía limpia', 1),
(188, 11, 'Energía renovable en la industria petrolera', 1),
(189, 11, 'Diseño de políticas de energías renovables', 1),
(190, 11, 'Ingeniería de sistemas de almacenamiento de energía', 0),
(191, 11, 'Desarrollo de sistemas de energía solar térmica', 1),
(192, 11, 'Consultoría en regulación y normativas energéticas', 1),
(193, 11, 'Innovación en turbinas y generadores eólicos', 1),
(194, 11, 'Proyectos de investigación en energía renovable', 1),

-- Textil y moda
(195, 12, 'Diseño de indumentaria deportiva innovadora', 1),
(196, 12, 'Producción de accesorios de moda sostenibles', 0),
(197, 12, 'Textiles inteligentes y wearables', 1),
(198, 12, 'Moda inclusiva y adaptativa', 1),
(199, 12, 'Producción de calzado eco-friendly', 0),
(200, 12, 'Diseño de moda ética y responsable', 1),
(201, 12, 'Tecnologías disruptivas en la industria textil', 1),
(202, 12, 'Creación de colecciones de moda artesanales', 1),
(203, 12, 'Diseño de tejidos y materiales innovadores', 0),
(204, 12, 'Moda y tecnología: wearables de última generación', 1),
(205, 12, 'Producción de ropa utilizando técnicas tradicionales', 1),
(206, 12, 'Diseño de patrones y técnicas de confección avanzadas', 1),
(207, 12, 'Moda circular y reciclaje textil', 0),
(208, 12, 'Creación de colecciones de alta costura', 1),
(209, 12, 'Diseño de moda para la diversidad corporal', 1),
(210, 12, 'Producción de telas ecológicas y biodegradables', 1),

-- Entretenimiento
(211, 13, 'Desarrollo de parques de entretenimiento tecnológico', 1),
(212, 13, 'Producción de contenido para realidad aumentada', 0),
(213, 13, 'Desarrollo de videojuegos educativos', 1),
(214, 13, 'Creación de atracciones de realidad virtual', 1),
(215, 13, 'Producción de espectáculos multimedia', 0),
(216, 13, 'Diseño de parques temáticos interactivos', 1),
(217, 13, 'Producción de contenido para plataformas streaming', 1),
(218, 13, 'Desarrollo de experiencias de entretenimiento inmersivo', 1),
(219, 13, 'Creación de juegos de mesa y estrategia', 0),
(220, 13, 'Producción de contenido para eventos culturales', 1),
(221, 13, 'Diseño de experiencias interactivas en museos', 1),
(222, 13, 'Desarrollo de contenido de realidad mixta', 1),
(223, 13, 'Producción de eventos de entretenimiento en vivo', 0),
(224, 13, 'Creación de parques de diversiones temáticos', 1),
(225, 13, 'Diseño de juegos de realidad aumentada', 1),
(226, 13, 'Producción de series y películas de animación', 1),

-- Arte y cultura
(227, 14, 'Gestión de galerías de arte contemporáneo', 1),
(228, 14, 'Producción de festivales culturales y artísticos', 0),
(229, 14, 'Promoción de artistas emergentes', 1),
(230, 14, 'Gestión de eventos culturales internacionales', 1),
(231, 14, 'Producción de obras teatrales y musicales', 0),
(232, 14, 'Gestión de museos y exhibiciones itinerantes', 1),
(233, 14, 'Promoción de arte urbano y street art', 1),
(234, 14, 'Organización de programas de residencias artísticas', 1),
(235, 14, 'Gestión de patrimonio cultural y arqueológico', 0),
(236, 14, 'Promoción de arte digital y nuevas expresiones', 1),
(237, 14, 'Gestión de eventos literarios y ferias del libro', 1),
(238, 14, 'Producción de música y conciertos en vivo', 1),
(239, 14, 'Promoción de danza contemporánea y tradicional', 0),
(240, 14, 'Gestión de programas de artistas en residencia', 1),
(241, 14, 'Producción de obras cinematográficas independientes', 1),
(242, 14, 'Promoción de la diversidad cultural y étnica', 1),
-- Investigación científica
(243, 15, 'Estudio de nuevos materiales nanotecnológicos', 1),
(244, 15, 'Investigación en biología sintética', 0),
(245, 15, 'Desarrollo de terapias génicas avanzadas', 1),
(246, 15, 'Investigación en inteligencia artificial ética', 1),
(247, 15, 'Estudios de neurociencia cognitiva avanzada', 0),
(248, 15, 'Investigación en energía de fusión nuclear', 1),
(249, 15, 'Desarrollo de técnicas de edición genética', 1),
(250, 15, 'Investigación en medicina regenerativa', 1),
(251, 15, 'Estudios de interacción ciencia-tecnología-sociedad', 0),
(252, 15, 'Investigación en biotecnología aplicada a la medicina', 1),
(253, 15, 'Desarrollo de tecnología cuántica', 1),
(254, 15, 'Investigación en sistemas inteligentes autónomos', 1),
(255, 15, 'Estudios de astrobiología y búsqueda de vida extraterrestre', 0),
(256, 15, 'Investigación en medicina personalizada', 1),
(257, 15, 'Desarrollo de nuevas técnicas de nanomedicina', 1),
(258, 15, 'Estudios de ciencia de datos y aprendizaje automático', 1),

-- Inmobiliaria
(259, 16, 'Desarrollo de proyectos inmobiliarios sostenibles', 1),
(260, 16, 'Gestión de propiedades residenciales de lujo', 0),
(261, 16, 'Inversiones inmobiliarias en ciudades inteligentes', 1),
(262, 16, 'Gestión de alquileres turísticos y vacacionales', 1),
(263, 16, 'Desarrollo de comunidades residenciales integradas', 0),
(264, 16, 'Gestión de propiedades comerciales estratégicas', 1),
(265, 16, 'Consultoría en inversión inmobiliaria internacional', 1),
(266, 16, 'Gestión de propiedades para inversión y rentabilidad', 1),
(267, 16, 'Desarrollo de proyectos inmobiliarios urbanos', 0),
(268, 16, 'Gestión de portafolios de propiedades residenciales', 1),
(269, 16, 'Inversiones inmobiliarias en desarrollo sostenible', 1),
(270, 16, 'Gestión de propiedades históricas y de patrimonio', 1),
(271, 16, 'Consultoría en inversión y financiación inmobiliaria', 0),
(272, 16, 'Desarrollo de proyectos de viviendas asequibles', 1),
(273, 16, 'Gestión de propiedades industriales y logísticas', 1),
(274, 16, 'Consultoría en planificación urbana y regeneración', 1),
-- Industria alimentaria
(275, 17, 'Investigación en nuevos métodos de conservación de alimentos', 1),
(276, 17, 'Creación de bebidas funcionales', 0),
(277, 17, 'Cocina molecular y técnicas avanzadas', 1),
(278, 17, 'Gestión de restaurantes de alta cocina', 1),
(279, 17, 'Diseño de experiencias gastronómicas innovadoras', 0),
(280, 17, 'Cultivo de hierbas aromáticas y especias', 1),
(281, 17, 'Producción de alimentos orgánicos certificados', 1),
(282, 17, 'Elaboración de chocolates artesanales', 1),
(283, 17, 'Desarrollo de nuevos métodos de empaque', 0),
(284, 17, 'Gastronomía fusionada de diferentes culturas', 1),
(285, 17, 'Cocina saludable y nutrición balanceada', 1),
(286, 17, 'Creación de menús para eventos especiales', 1),
(287, 17, 'Investigación en nutrición y alimentos saludables', 0),
(288, 17, 'Desarrollo de alimentos para dietas especiales', 1),
(289, 17, 'Producción de alimentos para mercados específicos', 1),
(290, 17, 'Innovación en procesamiento de alimentos', 1),
(291, 17, 'Desarrollo de productos alimenticios innovadores', 1),

-- Transporte y logística
(292, 18, 'Gestión de flotas de transporte sostenible', 1),
(293, 18, 'Logística de comercio electrónico y entregas rápidas', 0),
(294, 18, 'Transporte de carga especializada y pesada', 1),
(295, 18, 'Diseño de rutas logísticas eficientes', 1),
(296, 18, 'Logística inversa y gestión de devoluciones', 0),
(297, 18, 'Gestión de centros de distribución automatizados', 1),
(298, 18, 'Operaciones logísticas para comercio internacional', 1),
(299, 18, 'Transporte de productos perecederos y sensibles', 1),
(300, 18, 'Gestión de flotas de vehículos eléctricos', 0),
(301, 18, 'Logística para la industria farmacéutica', 1),
(302, 18, 'Soluciones logísticas para la industria automotriz', 1),
(303, 18, 'Gestión de inventario y control de almacenes', 1),
(304, 18, 'Transporte y logística para la industria aeroespacial', 0),
(305, 18, 'Gestión de cadena de suministro en tiempos de crisis', 1),
(306, 18, 'Logística para la distribución de productos tecnológicos', 1),
(307, 18, 'Servicios de transporte y logística personalizados', 1),
(308, 18, 'Innovación en sistemas de seguimiento y monitoreo', 1),

-- Publicidad y marketing
(309, 19, 'Consultoría estratégica de marketing digital', 1),
(310, 19, 'Gestión de campañas publicitarias omnicanal', 0),
(311, 19, 'Desarrollo de estrategias de posicionamiento SEO', 1),
(312, 19, 'Creación de contenido publicitario visual atractivo', 1),
(313, 19, 'Gestión de influencers y marketing de influencia', 0),
(314, 19, 'Diseño y desarrollo de sitios web orientados al usuario', 1),
(315, 19, 'Marketing de contenidos y storytelling de marca', 1),
(316, 19, 'Estrategias de marketing personalizado y CRM', 1),
(317, 19, 'Análisis de datos y métricas para marketing', 0),
(318, 19, 'Publicidad en redes sociales y estrategias de engagement', 1),
(319, 19, 'Marketing móvil y estrategias para dispositivos', 1),
(320, 19, 'Diseño de campañas publicitarias innovadoras', 1),
(321, 19, 'Publicidad programática y automatización', 0),
(322, 19, 'Desarrollo de estrategias de marketing viral', 1),
(323, 19, 'Consultoría en branding y construcción de marca', 1),
(324, 19, 'Publicidad nativa y contenido patrocinado', 1),
(325, 19, 'Marketing de productos y lanzamientos de marca', 1),

-- Servicios legales
(326, 20, 'Asesoramiento legal en fusiones y adquisiciones', 1),
(327, 20, 'Servicios legales para startups y emprendedores', 0),
(328, 20, 'Litigios y resolución alternativa de conflictos', 1),
(329, 20, 'Asesoría legal en propiedad intelectual', 1),
(330, 20, 'Consultoría en cumplimiento normativo y ética empresarial', 0),
(331, 20, 'Asesoramiento legal en contratos comerciales', 1),
(332, 20, 'Derecho laboral y recursos humanos', 1),
(333, 20, 'Asesoría legal para el sector inmobiliario', 1),
(334, 20, 'Servicios legales en tecnología y propiedad digital', 0),
(335, 20, 'Asesoramiento legal en asuntos internacionales', 1),
(336, 20, 'Consultoría en derecho ambiental y sostenibilidad', 1),
(337, 20, 'Asesoramiento en regulación de nuevas tecnologías', 1),
(338, 20, 'Defensa y representación legal en litigios civiles', 0),
(339, 20, 'Servicios legales para industrias reguladas', 1),
(340, 20, 'Asesoramiento en derecho bancario y financiero', 1),
(341, 20, 'Consultoría legal en protección de datos y privacidad', 1),
(342, 20, 'Asesoría legal para el sector de la salud', 1),
(343, 21, 'Investigación en terapias génicas avanzadas', 1),
(344, 21, 'Desarrollo de cultivos transgénicos sostenibles', 0),
(345, 21, 'Biotecnología para la mejora de cultivos agrícolas', 1),
(346, 21, 'Investigación en bioingeniería de tejidos', 1),
(347, 21, 'Desarrollo de biofármacos y medicina personalizada', 0),
(348, 21, 'Biotecnología para la conservación de especies', 1),
(349, 21, 'Investigación en bioprocesos industriales', 1),
(350, 21, 'Desarrollo de biocombustibles y energías renovables', 1),
(351, 21, 'Biotecnología aplicada a la producción de alimentos', 0),
(352, 21, 'Investigación en nanotecnología y bioingeniería', 1),
(353, 21, 'Desarrollo de terapias celulares regenerativas', 1),
(354, 21, 'Biotecnología para la remediación ambiental', 1),
(355, 21, 'Investigación en biotecnología marina y acuática', 0),
(356, 21, 'Desarrollo de vacunas avanzadas y terapias inmunológicas', 1),
(357, 21, 'Biotecnología para la mejora de la salud animal', 1),
(358, 21, 'Investigación en biotecnología forense y criminalística', 1),
(359, 21, 'Biotecnología aplicada a la industria textil y moda', 1),

-- Robótica aplicada
(360, 22, 'Desarrollo de robots asistenciales para personas mayores', 1),
(361, 22, 'Robótica para la educación y el aprendizaje', 0),
(362, 22, 'Desarrollo de robots autónomos para logística', 1),
(363, 22, 'Robótica aplicada a la agricultura de precisión', 1),
(364, 22, 'Desarrollo de exoesqueletos y prótesis robóticas', 0),
(365, 22, 'Robots colaborativos para la industria manufacturera', 1),
(366, 22, 'Diseño de robots para exploración submarina', 1),
(367, 22, 'Robótica para la asistencia en cirugía y medicina', 1),
(368, 22, 'Desarrollo de drones y vehículos aéreos no tripulados', 0),
(369, 22, 'Robots sociales y compañeros de asistencia personal', 1),
(370, 22, 'Integración de robots en la atención sanitaria', 1),
(371, 22, 'Robótica aplicada a la industria del entretenimiento', 1),
(372, 22, 'Robots para el monitoreo y mantenimiento de infraestructuras', 0),
(373, 22, 'Desarrollo de robots para la exploración espacial', 1),
(374, 22, 'Robótica para aplicaciones en seguridad y defensa', 1),
(375, 22, 'Robots inteligentes para el cuidado del medio ambiente', 1),
(376, 22, 'Robótica aplicada a la investigación científica', 1),

-- Realidad virtual y aumentada
(377, 23, 'Desarrollo de aplicaciones de RV/RA para el sector educativo', 1),
(378, 23, 'RV/RA para experiencias inmersivas en turismo y viajes', 0),
(379, 23, 'Aplicaciones de RV/RA para el entrenamiento laboral', 1),
(380, 23, 'Simulaciones médicas y aplicaciones en salud', 1),
(381, 23, 'Entretenimiento y juegos de RV/RA innovadores', 0),
(382, 23, 'Aplicaciones de RV/RA para la arquitectura y diseño', 1),
(383, 23, 'RV/RA en marketing y publicidad interactiva', 1),
(384, 23, 'Entornos virtuales para colaboración y teletrabajo', 1),
(385, 23, 'Aplicaciones de RV/RA en eventos y espectáculos', 0),
(386, 23, 'RV/RA para terapias y tratamientos psicológicos', 1),
(387, 23, 'Entrenamiento militar y aplicaciones de defensa', 1),
(388, 23, 'Aplicaciones de RV/RA para la industria automotriz', 1),
(389, 23, 'RV/RA en simulaciones de procesos industriales', 0),
(390, 23, 'Aplicaciones de RV/RA para la exploración espacial', 1),
(391, 23, 'Realidad aumentada aplicada a la logística y transporte', 1),
(392, 23, 'RV/RA para el diseño de moda y textiles', 1),
(393, 23, 'Aplicaciones de RV/RA para la investigación científica', 1),
(394, 24, 'Desarrollo de tecnologías para la exploración lunar', 1),
(395, 24, 'Investigación en tecnologías de propulsión espacial', 0),
(396, 24, 'Diseño de vehículos espaciales para misiones interplanetarias', 1),
(397, 24, 'Exploración de asteroides y recursos espaciales', 1),
(398, 24, 'Investigación en hábitats para la colonización espacial', 0),
(399, 24, 'Desarrollo de sistemas de soporte vital para el espacio', 1),
(400, 24, 'Estudios de astrobiología y búsqueda de vida extraterrestre', 1),
(401, 24, 'Exploración y mapeo de planetas y lunas del sistema solar', 1),
(402, 24, 'Investigación en telecomunicaciones y redes espaciales', 0),
(403, 24, 'Desarrollo de tecnologías para viajes interestelares', 1),
(404, 24, 'Exploración y observación astronómica desde el espacio', 1),
(405, 24, 'Investigación en ciencia de materiales para aplicaciones espaciales', 1),
(406, 24, 'Desarrollo de tecnología para la exploración de Marte', 0),
(407, 24, 'Investigación en navegación y posicionamiento en el espacio', 1),
(408, 24, 'Exploración del universo a través de sondas espaciales', 1),
(409, 24, 'Desarrollo de tecnología para estaciones espaciales', 1),
(410, 24, 'Exploración espacial para la preservación de la Tierra', 1),


-- Blockchain y criptomonedas
(411, 25, 'Desarrollo de aplicaciones descentralizadas (DApps)', 1),
(412, 25, 'Investigación en interoperabilidad entre blockchains', 0),
(413, 25, 'Criptoeconomía y diseño de modelos de incentivos', 1),
(414, 25, 'Desarrollo de tokens no fungibles (NFTs) y su aplicación', 1),
(415, 25, 'Investigación en escalabilidad y rendimiento de blockchains', 0),
(416, 25, 'Blockchain para la gestión de identidad digital', 1),
(417, 25, 'Desarrollo de plataformas de contratos inteligentes', 1),
(418, 25, 'Investigación en privacidad y seguridad en blockchain', 1),
(419, 25, 'Criptomonedas estables (Stablecoins) y su implementación', 0),
(420, 25, 'Blockchain en la industria de la cadena de suministro', 1),
(421, 25, 'Desarrollo de infraestructura para exchanges de criptomonedas', 1),
(422, 25, 'Investigación en regulación y marcos legales para cripto', 1),
(423, 25, 'Blockchain en la industria de la salud y registros médicos', 0),
(424, 25, 'Aplicaciones de blockchain en la industria energética', 1),
(425, 25, 'Desarrollo de soluciones de financiamiento descentralizado', 1),
(426, 25, 'Investigación en oráculos y datos externos en blockchains', 1),
(427, 25, 'Blockchain y criptomonedas para servicios financieros', 1),

-- Diseño de experiencias
(428, 26, 'Experiencias de usuario (UX) para plataformas digitales', 1),
(429, 26, 'Diseño de experiencias inmersivas en entornos virtuales', 0),
(430, 26, 'Creación de experiencias sensoriales en eventos en vivo', 1),
(431, 26, 'Diseño de interfaces de usuario (UI) innovadoras', 1),
(432, 26, 'Experiencias de marca y storytelling emocional', 0),
(433, 26, 'Diseño de espacios interactivos y museografía', 1),
(434, 26, 'Creación de experiencias de compra y retail experiencial', 1),
(435, 26, 'Diseño de experiencias educativas inmersivas', 1),
(436, 26, 'Experiencias de entretenimiento y parques temáticos', 0),
(437, 26, 'Diseño de experiencias gastronómicas innovadoras', 1),
(438, 26, 'Experiencias de marca en el ámbito digital y redes sociales', 1),
(439, 26, 'Diseño de experiencias en viajes y turismo', 1),
(440, 26, 'Creación de experiencias culturales y artísticas', 0),
(441, 26, 'Diseño de experiencias en realidad virtual y aumentada', 1),
(442, 26, 'Experiencias de bienestar y mindfulness', 1),
(443, 26, 'Diseño de experiencias para la industria automotriz', 1),
(444, 26, 'Experiencias personalizadas y adaptativas', 1),
(445, 27, 'Desarrollo de sistemas de IA para la toma de decisiones éticas', 1),
(446, 27, 'Investigación en algoritmos de IA transparentes y explicables', 0),
(447, 27, 'Ética en la recopilación y uso de datos para IA', 1),
(448, 27, 'Desarrollo de IA para la detección de sesgos y discriminación', 1),
(449, 27, 'Investigación en responsabilidad y rendición de cuentas en IA', 0),
(450, 27, 'Ética en la implementación de IA en sistemas críticos', 1),
(451, 27, 'Desarrollo de políticas y regulaciones para IA ética', 1),
(452, 27, 'Investigación en privacidad y protección de datos en IA', 1),
(453, 27, 'Ética en el diseño de sistemas de IA centrados en el ser humano', 0),
(454, 27, 'Desarrollo de IA para la igualdad y equidad social', 1),
(455, 27, 'Investigación en ética para la IA en la salud y medicina', 1),
(456, 27, 'Ética en la automatización y el impacto laboral de la IA', 1),
(457, 27, 'Desarrollo de IA para la sostenibilidad y el medio ambiente', 0),
(458, 27, 'Investigación en IA y seguridad cibernética ética', 1),
(459, 27, 'Ética en el uso de IA para la toma de decisiones legales', 1),
(460, 27, 'Desarrollo de sistemas de IA para la educación ética', 1),
(461, 27, 'Investigación en ética para la IA en el entretenimiento', 1),

-- Sostenibilidad urbana
(462, 28, 'Planificación urbana sostenible y desarrollo de ciudades inteligentes', 1),
(463, 28, 'Sistemas de transporte público eficiente y sostenible', 0),
(464, 28, 'Desarrollo de infraestructuras energéticas sostenibles', 1),
(465, 28, 'Diseño de espacios verdes y áreas recreativas urbanas', 1),
(466, 28, 'Gestión de residuos y reciclaje en entornos urbanos', 0),
(467, 28, 'Edificaciones sostenibles y eficiencia energética', 1),
(468, 28, 'Promoción de movilidad urbana sostenible y no motorizada', 1),
(469, 28, 'Desarrollo de proyectos de vivienda sostenible', 1),
(470, 28, 'Resiliencia urbana y adaptación al cambio climático', 0),
(471, 28, 'Economía circular y prácticas sostenibles en la industria', 1),
(472, 28, 'Reducción de la huella de carbono en entornos urbanos', 1),
(473, 28, 'Innovación en infraestructura verde y azoteas ecológicas', 1),
(474, 28, 'Acceso equitativo a servicios básicos en áreas urbanas', 0),
(475, 28, 'Promoción de la movilidad eléctrica y energías renovables', 1),
(476, 28, 'Rescate y preservación de espacios históricos urbanos', 1),
(477, 28, 'Desarrollo de tecnologías para la gestión inteligente de ciudades', 1),

-- Gestión de riesgos
(478, 29, 'Evaluación y gestión de riesgos empresariales', 1),
(479, 29, 'Análisis y control de riesgos financieros', 0),
(480, 29, 'Gestión de riesgos en proyectos de inversión', 1),
(481, 29, 'Prevención y gestión de riesgos de desastres naturales', 1),
(482, 29, 'Evaluación y gestión de riesgos en el sector de seguros', 0),
(483, 29, 'Gestión de riesgos geopolíticos y comerciales internacionales', 1),
(484, 29, 'Identificación y gestión de riesgos en la cadena de suministro', 1),
(485, 29, 'Gestión de riesgos en mercados financieros y de capitales', 1),
(486, 29, 'Análisis y gestión de riesgos operativos', 0),
(487, 29, 'Gestión de riesgos de ciberseguridad y protección de datos', 1),
(488, 29, 'Evaluación y gestión de riesgos en el sector de salud', 1),
(489, 29, 'Gestión de riesgos medioambientales y sostenibilidad', 1),
(490, 29, 'Identificación y gestión de riesgos en el ámbito legal', 0),
(491, 29, 'Gestión de riesgos en la industria energética y recursos naturales', 1),
(492, 29, 'Gestión de riesgos en proyectos de construcción e infraestructura', 1),
(493, 29, 'Análisis y gestión de riesgos en el sector tecnológico', 1),

-- Bioingeniería molecular
(494, 30, 'Diseño de biomateriales para medicina regenerativa', 1),
(495, 30, 'Desarrollo de terapias génicas y celulares', 0),
(496, 30, 'Investigación en ingeniería de tejidos y órganos artificiales', 1),
(497, 30, 'Bioinformática y análisis de datos en biología molecular', 1),
(498, 30, 'Desarrollo de nanotecnología aplicada a la biomedicina', 0),
(499, 30, 'Investigación en biología sintética y diseño de sistemas biológicos', 1),
(500, 30, 'Ingeniería metabólica para la producción de biocombustibles', 1),
(501, 30, 'Desarrollo de biosensores y diagnóstico molecular', 1),
(502, 30, 'Investigación en terapias contra el envejecimiento y longevidad', 0),
(503, 30, 'Bioingeniería aplicada a la producción de alimentos sostenibles', 1),
(504, 30, 'Desarrollo de sistemas de entrega de fármacos basados en nanotecnología', 1),
(505, 30, 'Investigación en bioenergía y biocombustibles avanzados', 1),
(506, 30, 'Ingeniería de proteínas y diseño molecular', 0),
(507, 30, 'Desarrollo de tecnologías de edición genética', 1),
(508, 30, 'Investigación en neuroingeniería y interfaces cerebro-máquina', 1),
(509, 30, 'Bioingeniería ambiental y bioremediación', 1),
(510, 30, 'Aplicaciones de bioingeniería en la industria farmacéutica', 1);

